using System.Collections.Generic;

namespace Underleague.Game.Ui;

/// <summary>
/// Textos de la interfaz por clave (RT-073). Todo lo que el jugador lee sale de aquí o de
/// <c>data/l10n/&lt;idioma&gt;/templates.json</c> a través de <c>Sim.Data.Localization</c>; en la pantalla
/// no hay ni una cadena escrita a mano.
/// <para>
/// El vocabulario del juego —posiciones, atributos, rasgos, etiquetas, relaciones de vínculo— ya vive en
/// <c>data/l10n</c> y se lee del catálogo. Lo que hay en esta tabla es solo el <b>mobiliario de la
/// pantalla</b> (títulos, ayudas de control, etiquetas de campo), que todavía no tiene fichero de datos.
/// La tabla está indexada por clave precisamente para que en fase 4 el cuerpo de <see cref="Get(string)"/>
/// pase a leer <c>data/l10n/&lt;idioma&gt;/ui.json</c> sin tocar ninguna pantalla.
/// </para>
/// </summary>
public static class UiText
{
    private static readonly Dictionary<string, string> Es = new()
    {
        ["ui.team.title"] = "EQUIPO",
        ["ui.team.subtitle"] = "{0} · {1} · plantilla de {2}",
        ["ui.team.roster"] = "PLANTILLA",
        ["ui.team.placeholderClub"] = "club de pruebas",
        ["ui.team.starters"] = "TITULARES",
        ["ui.team.bench"] = "SUPLENTES",
        ["ui.team.pitch"] = "COLOCACIÓN",
        ["ui.team.pitchHint"] = "mitad propia, 8 columnas · el portero no se mueve de su casilla",
        ["ui.team.coverage"] = "COBERTURA DEL EQUIPO",
        ["ui.team.coverageLegend"] = "cubren",
        ["ui.team.coverageButton"] = "Cobertura del equipo (X / C)",
        ["ui.team.coverageHint"] = "jugadores que cubren cada casilla · {0} casillas sin cubrir",
        ["ui.team.coverageHole"] = "hueco",
        ["ui.team.legendZone"] = "zona: aquí estará",
        ["ui.team.legendMargin"] = "margen: hasta aquí llega",
        ["ui.team.legendLink"] = "vínculo",
        ["ui.team.legendCreated"] = "se crea",
        ["ui.team.legendBroken"] = "se rompe",
        ["ui.team.links"] = "VÍNCULOS",
        ["ui.team.lineup"] = "ALINEACIÓN",
        ["ui.team.lineupRow"] = "{0} · {1} · columna {2}, fila {3} · {4} {5}",
        ["ui.team.linkOne"] = "vínculo",
        ["ui.team.linkMany"] = "vínculos",
        ["ui.team.moreChanges"] = "y {0} cambios más en el resto de la alineación",

        // Aviso al soltar a un jugador (RF-012d): un perk que se enciende o se apaga por la casilla es
        // exactamente el tipo de consecuencia que no puede descubrirse en el informe post-partido.
        ["ui.team.perkOn"] = "✔ {0} se activa aquí",
        ["ui.team.perkOff"] = "✘ {0} no se activa aquí",
        ["ui.team.perkOnOther"] = "✔ {0} de {1} se activa",
        ["ui.team.perkOffOther"] = "✘ {0} de {1} se desactiva",

        // Lo que Equipo no deja hacer, dicho (BX-1): un movimiento que no ocurre sin explicación es lo que el
        // revisor vivió como «no me dejaba alinear».
        ["ui.team.refuse.out"] = "{0} no puede jugar: no se puede alinear a un lisiado ni a un muerto",
        ["ui.team.refuse.full"] = "Ya hay siete titulares: suelta sobre uno de ellos para cambiarlo",
        ["ui.team.refuse.cell"] = "{0} no puede ir en esa casilla",

        // Modo de zonas: el vocabulario que usan los perks de inicio y de vínculo, dibujado sobre la
        // cuadrícula que describen. Los nombres de los tercios y de las bandas NO están aquí: salen de
        // data/l10n/<idioma>/templates.json, que es de donde salen también las descripciones de los perks.
        ["ui.team.zonesButton"] = "Zonas del campo (Y / Z)",
        ["ui.team.zones"] = "ZONAS DE INICIO Y VÍNCULOS",
        ["ui.team.zonesHelp"] =
            "Los perks de inicio miran la casilla en la que alineas al jugador, no dónde acabe él durante el "
            + "partido.\n\nEl tercio lo da la columna de esa casilla; la banda, la fila: es banda cualquier "
            + "fila menos la 2, que es la fila central.\n\nUn vínculo une a dos titulares que estén a "
            + "dos casillas o menos en la dirección que pide el perk (delante, detrás, izquierda, derecha o "
            + "en diagonal).",
        ["ui.link.Beside"] = "al lado",
        ["ui.link.Ahead"] = "delante",
        ["ui.link.Behind"] = "detrás",
        ["ui.link.Left"] = "izquierda",
        ["ui.link.Right"] = "derecha",
        ["ui.link.DiagonalAhead"] = "diagonal delante",
        ["ui.link.DiagonalBehind"] = "diagonal detrás",
        ["ui.team.linksNone"] = "sin vínculos: nadie en las casillas contiguas",
        ["ui.team.linkOf"] = "{0}: {1}",
        ["ui.team.created"] = "+ {1} ({0})",
        ["ui.team.broken"] = "- {1} ({0})",
        ["ui.team.moving"] = "MOVIENDO A {0}",
        ["ui.team.dropHint"] = "suelta en una casilla de la mitad propia",
        ["ui.team.selected"] = "SELECCIONADO",
        ["ui.team.nobody"] = "selecciona a un jugador para ver su zona de acción",
        ["ui.card.average"] = "media",
        ["ui.card.level"] = "nivel {0}",
        ["ui.card.rarity.Common"] = "común",
        ["ui.card.rarity.Rare"] = "raro",
        ["ui.card.rarity.Legendary"] = "legendario",
        ["ui.card.traits"] = "RASGOS",
        ["ui.card.perks"] = "PERKS",
        ["ui.card.perkRequirement"] = "{0}: {1} de {2} en la plantilla",
        ["ui.card.ability"] = "HABILIDAD RACIAL",

        // Carrera (RF-122, ADR 0124, F1 §6): CareerLines omite toda cifra a cero salvo los partidos, así
        // que solo hacen falta el singular y el plural de cada campo mostrado.
        ["ui.card.career"] = "CARRERA",
        ["ui.card.careerMatches"] = "{0} partidos",
        ["ui.card.careerMatch"] = "1 partido",
        ["ui.card.careerGoals"] = "{0} goles",
        ["ui.card.careerGoal"] = "1 gol",
        ["ui.card.careerTacklesWon"] = "{0} entradas ganadas",
        ["ui.card.careerTackleWon"] = "1 entrada ganada",
        ["ui.card.careerInjuriesCaused"] = "{0} lesiones causadas",
        ["ui.card.careerInjuryCaused"] = "1 lesión causada",
        ["ui.card.careerDeathsCaused"] = "{0} muertes causadas",
        ["ui.card.careerDeathCaused"] = "1 muerte causada",
        ["ui.card.perkSlot"] = "slot libre",
        ["ui.card.item"] = "OBJETO",
        ["ui.card.itemNone"] = "sin objeto (equipamiento: fase 2)",
        ["ui.card.state"] = "ESTADO",
        ["ui.card.salary"] = "SALARIO",
        ["ui.card.salaryNone"] = "sin salario (economía: fase 2)",
        ["ui.card.links"] = "VÍNCULOS",
        ["ui.card.style"] = "estilo",
        ["ui.card.bench"] = "suplente",
        ["ui.state.Healthy"] = "sano",
        ["ui.state.MinorInjury"] = "lesión leve",
        ["ui.state.SevereInjury"] = "lesión grave",
        ["ui.state.Dead"] = "muerto",
        ["ui.pos.Goalkeeper"] = "POR",
        ["ui.pos.Defender"] = "DEF",
        ["ui.pos.Midfielder"] = "CEN",
        ["ui.pos.Forward"] = "DEL",
        ["ui.input.mouse"] = "RATÓN  clic: seleccionar · arrastrar y soltar: colocar · clic en la ficha: expandir (un suplente se coge y se suelta en el campo igual que un titular)",
        ["ui.input.pad"] = "MANDO  cruceta: mover cursor · A: seleccionar y coger/soltar (también un suplente, igual que un titular) · B: cancelar · X: cobertura · Y: zonas",

        // --- esqueleto jugable (docs/ui-run-minima.md) ---
        ["ui.nav.back"] = "Volver",
        ["ui.nav.map"] = "Volver al mapa",
        ["ui.nav.team"] = "Equipo",
        ["ui.nav.continue"] = "Continuar",
        ["ui.pause.title"] = "Pausa",
        ["ui.pause.resume"] = "Resumir",
        ["ui.pause.save"] = "Guardar",
        ["ui.pause.saved"] = "Run guardada.",
        // RT-061: el guardado es ironman y automático; el botón no crea un segundo slot ni un punto al que volver.
        ["ui.pause.autosave"] = "También se guarda sola al completar cada nodo.",
        ["ui.pause.settings"] = "Ajustes",
        ["ui.pause.quit"] = "Salir al menú principal",
        ["ui.settings.music"] = "Música",
        ["ui.settings.effects"] = "Efectos",
        ["ui.settings.match2dKey"] = "F3: vista 2D del partido",
        ["ui.settings.match2dKeyHint"] = "Con la opción activa, F3 alterna en la retransmisión.",
        ["ui.settings.dev"] = "Desarrollo",
        ["ui.settings.debugView"] = "Partido en vista 2D",
        ["ui.settings.debugViewHint"] = "Tick a tick y con el log de eventos. F3 vuelve a la retransmisión.",
        ["ui.nav.pendingTitle"] = "PANTALLA PENDIENTE",
        ["ui.nav.pendingBody"] = "{0} todavía no existe: la escribe el otro paquete de la interfaz mínima. La run no se bloquea por eso.",
        ["ui.nav.pendingMatch"] = "Se juega el partido aquí de forma provisional: se resuelve y se enseña el resultado, sin log y sin informe.",

        ["ui.start.title"] = "Knavall",
        ["ui.start.kn.tagline"] = "Rise to Rule",
        ["ui.start.kn.choose"] = "Elige tu clan",
        ["ui.start.kn.gold"] = "Oro inicial: {0}",
        ["ui.start.kn.random"] = "Al azar",
        ["ui.start.kn.inputMouse"] = "RATÓN  clic en un clan: elegirlo · pasa el ratón por un cartel: qué significa",
        ["ui.start.kn.beginTip"] = "Empieza una run nueva con el clan elegido: tres actos, veinte partidos y el derecho a gobernar para quien sobreviva.",
        ["ui.start.kn.continueTip"] = "Vuelve a la run guardada, donde la dejaste.",
        ["ui.start.subtitle"] = "carnicería administrada · esqueleto jugable de la fase 2",
        ["ui.start.club"] = "CLUB",
        ["ui.start.clubHint"] = "todos los jugadores del club inicial son de una misma raza",
        ["ui.start.seed"] = "SEMILLA",
        ["ui.start.seedHint"] = "la misma semilla juega la misma run: mismos mapas, mismos rivales, mismos dados",
        ["ui.start.random"] = "Aleatoria",
        ["ui.start.begin"] = "Empezar run",
        ["ui.start.continue"] = "Continuar la run guardada",
        ["ui.start.noSave"] = "no hay ninguna run guardada",
        ["ui.start.saved"] = "hay una run guardada: acto {0}, {1} de oro, {2} disponibles",
        ["ui.start.ability"] = "habilidad racial",
        ["ui.start.chosen"] = "elegido: {0}",
        ["ui.start.badSeed"] = "la semilla debe ser un número entero; se usa {0}",

        ["ui.map.title"] = "MAPA",
        ["ui.map.subtitle"] = "acto {0} de {1} · {2} · {3} de oro",
        ["ui.map.available"] = "DISPONIBLES {0} / mínimo {1}",
        ["ui.map.availableHint"] = "por debajo del mínimo la run termina",
        ["ui.map.choose"] = "ADÓNDE IR",
        ["ui.map.graph"] = "ACTO {0}",
        ["ui.map.progress"] = "nodo {0} de la run · {1} nodos por acto",
        ["ui.map.marketHere"] = "mercado: la única tienda del juego",
        ["ui.map.marketHops"] = "mercado a {0} saltos desde aquí",
        ["ui.map.marketNone"] = "sin mercado alcanzable por este camino",
        ["ui.map.difficulty"] = "dificultad {0}/5 · {1}",
        ["ui.bet.refunded"] = "el corredor te devuelve {0} de oro",
        ["ui.map.betTaken"] = "apuesta hecha: {0} de oro",
        ["ui.map.refereeLine"] = "pita {0} · {1}",
        ["ui.map.boss"] = "jefe del acto {0}",
        ["ui.map.bossHidden"] = "su modificador de regla no se conoce hasta llegar",
        ["ui.map.legend"] = "dorado = accesible · relleno = recorrido · apagado = fuera de alcance",
        ["ui.map.state"] = "ESTADO DE LA RUN",
        ["ui.map.roster"] = "plantilla {0} de {1} · {2} caídos",
        ["ui.map.quit"] = "Guardar y salir",
        ["ui.map.abandon"] = "Abandonar la run",
        ["ui.map.abandonSure"] = "¿Seguro? Se pierde",
        ["ui.map.noNodes"] = "no hay nodos accesibles",

        // Leyenda de iconos (encargo mapa-pregon, UI-002): un icono, un nombre —ya en ui.kind.*— y qué es,
        // por cada uno de los ocho NodeKind.
        ["ui.map.legend.title"] = "LEYENDA",
        ["ui.map.legend.LeagueMatch"] = "un rival cualquiera; da oro",
        ["ui.map.legend.EliteMatch"] = "más riesgo, más recompensa",
        ["ui.map.legend.Market"] = "la única tienda del juego",
        ["ui.map.legend.Clinic"] = "cura garantizada, cuesta caro",
        ["ui.map.legend.Training"] = "mejora sin arriesgar a la plantilla",
        ["ui.map.legend.Event"] = "algo pasa; no siempre bueno",
        ["ui.map.legend.Boss"] = "perderlo termina la run",

        // El periódico deportivo de humor negro (encargo mapa-pregon, RA-025): cabecera y lema fijos,
        // titular elegido de un repertorio, y breves que en parte reaccionan al estado real de la run
        // (ui.newspaper.brief.*) y en parte son del mismo repertorio de broma (ui.newspaper.filler.*).
        ["ui.newspaper.masthead"] = "EL SILBATO NEGRO",
        ["ui.newspaper.lema"] = "«Noticias mientras queden jugadores para leerlas»",
        ["ui.newspaper.headline.0"] = "EL ÁRBITRO DEL PRÓXIMO CRUCE YA HA COBRADO SU SOBRE",
        ["ui.newspaper.headline.1"] = "LA CLÍNICA DEL BARRIO ABRE 24 HORAS «POR SI ACASO»",
        ["ui.newspaper.headline.2"] = "UN PATROCINADOR ANÓNIMO REGALA SEGURO DE VIDA... AL RIVAL",
        ["ui.newspaper.headline.3"] = "EL MERCADO NEGRO DE PRÓTESIS BATE RÉCORD DE VENTAS",
        ["ui.newspaper.headline.4"] = "LA FEDERACIÓN NIEGA QUE EL BALÓN LLEVE PINCHOS: «ES LA COSTURA»",
        ["ui.newspaper.headline.5"] = "EL COMITÉ DE ÉTICA SE TOMA UNAS VACACIONES INDEFINIDAS",
        ["ui.newspaper.filler.0"] = "El vestuario visitante pide un cura antes que un fisio.",
        ["ui.newspaper.filler.1"] = "Venden entradas para la grada y para el quirófano en la misma taquilla.",
        ["ui.newspaper.filler.2"] = "El seguro del club cubre fracturas; la lápida va aparte.",
        ["ui.newspaper.filler.3"] = "El fichaje nuevo viene con garantía de seis meses, o de vida.",
        ["ui.newspaper.filler.4"] = "El banquillo ya no cabe: hay más muletas que jugadores.",
        ["ui.newspaper.filler.5"] = "El árbitro pita penalti antes de empezar, «por si las moscas».",
        ["ui.newspaper.filler.6"] = "La grada aplaude más fuerte cuando cae alguien que un gol.",
        ["ui.newspaper.filler.7"] = "El taller de implantes abre franquicia junto al campo.",
        ["ui.newspaper.brief.death"] = "1 baja esta run; el utilero ya recicló la taquilla vacía.",
        ["ui.newspaper.brief.deaths"] = "{0} bajas esta run; el utilero ya recicló las taquillas vacías.",
        ["ui.newspaper.brief.deathsAlt.0"] = "Cero bajas por ahora; el forense se queja de que no le sale ni el alquiler.",
        ["ui.newspaper.brief.deathsAlt.1"] = "Ni una baja esta run; el forense ya mira otro club.",
        ["ui.newspaper.brief.gold"] = "La tesorería declara {0} de oro; media va prometida al forense.",
        ["ui.newspaper.brief.goldAlt.0"] = "Caja a cero: el oro «está invertido en ataúdes de kilometraje».",
        ["ui.newspaper.brief.goldAlt.1"] = "Sin un cobre en caja; el club acepta pagos en órganos de repuesto.",
        ["ui.newspaper.brief.matches"] = "{0} victorias y {1} derrotas esta run; la grada solo aplaude las derrotas.",
        ["ui.newspaper.brief.matchesAlt.0"] = "Ningún partido jugado todavía; el árbitro ya ensaya el silbato.",
        ["ui.newspaper.brief.matchesAlt.1"] = "Marcador sin estrenar esta run; la grada espera con paciencia de buitre.",
        ["ui.newspaper.brief.severe"] = "{0} con lesión grave; la clínica cobra por adelantado, «no vaya a ser».",
        ["ui.newspaper.brief.severeAlt.0"] = "Ni una lesión grave hoy; el mortero de la clínica cría polvo.",
        ["ui.newspaper.brief.severeAlt.1"] = "Plantilla sin lesiones graves; la clínica se queja de que así no hay negocio.",

        ["ui.scout.title"] = "OJEO",
        ["ui.scout.subtitle"] = "{0} · dificultad {1}/5 · {2}",
        ["ui.scout.rival"] = "PLANTILLA RIVAL",
        ["ui.scout.build"] = "BUILD",
        ["ui.scout.buildLine"] = "{0} · nivel medio {1} · {2}",
        ["ui.scout.referee"] = "ÁRBITRO",
        ["ui.scout.mob"] = "SI HAY EMPATE, LA TURBA",
        ["ui.scout.mobLine"] = "{0}: {1}",
        ["ui.scout.refereeLine"] = "{0} · {1}",
        ["ui.scout.refereeCatchphrase"] = "«{0}»",
        ["ui.scout.refereeMemoryKnown"] = "se acuerda de ti: {0}",
        ["ui.scout.refereeMemoryNone"] = "no te conoce",
        ["ui.scout.refereeStart"] = "el partido empieza con criterio {0}",
        ["ui.scout.refereeBlindTop"] = "es tuerto: no ve la banda de arriba",
        ["ui.scout.refereeBlindBottom"] = "es tuerto: no ve la banda de abajo",
        ["ui.scout.lethal"] = "PERKS LETALES",
        ["ui.scout.lethalNone"] = "ninguno: este rival no puede matar a nadie",
        ["ui.scout.lethalLine"] = "{0} lleva {1}: {2}",
        ["ui.scout.risk"] = "RIESGO DE MUERTE DE TUS TITULARES",
        ["ui.scout.riskLine"] = "{0}: {1}",
        ["ui.scout.riskNone"] = "sin riesgo de muerte con esta alineación",

        // Nombre corto del rasgo del árbitro (ADR 0158 §2): distinto de la línea larga que compone
        // Sim.Run.View.RefereeView desde data/l10n/<idioma>/templates.json (RT-035) -esta es solo la
        // etiqueta de la ficha, "rasgo: Estricto", nunca el texto de lo que hace.
        ["ui.refereeTrait.Neutral"] = "Neutro",
        ["ui.refereeTrait.Strict"] = "Estricto",
        ["ui.refereeTrait.Lenient"] = "Permisivo",
        ["ui.refereeTrait.Homer"] = "Casero",
        ["ui.refereeTrait.OneEyed"] = "Tuerto",
        ["ui.refereeTrait.Cowardly"] = "Cobarde",
        ["ui.refereeTrait.Corrupt"] = "Corrupto",
        ["ui.refereeTrait.Incorruptible"] = "Incorruptible",
        ["ui.scout.warnings"] = "ANTES DE CONFIRMAR",
        // ADR 0134: hasta entonces este aviso saltaba con la alineación GUARDADA incompleta y mentía —el
        // once se rellenaba solo hasta siete—. Ahora solo sale cuando la inferioridad es real, y dice con
        // cuántos se juega en vez de llevar el 5 escrito dentro.
        ["ui.scout.warnShorthanded"] = "juegas en inferioridad: solo hay {0} para el campo, y con 5 una sola baja termina la run",
        ["ui.scout.warnFilled"] = "{0} sale de oficio: tú no lo alineaste, y el hueco lo ha tapado el equipo",
        ["ui.scout.warnShortByChoice"] = "juegas con {0} porque lo has decidido: con 5 en campo una sola baja termina la run",
        ["ui.scout.leaveGap"] = "Dejar el hueco vacío",
        ["ui.scout.fillGap"] = "Que el banquillo tape el hueco",
        ["ui.scout.startersFilled"] = "de oficio",
        ["ui.scout.warnCap"] = "{0} lleva 3/3 prótesis: una lesión grave lo deja lisiado, sin cura",
        ["ui.scout.warnSevere"] = "{0} sale con una lesión grave sin tratar: si vuelve a lesionarse, muere",
        ["ui.scout.warnLethal"] = "{0} puede morir en este partido: {1}",
        ["ui.scout.lineup"] = "Alinear",
        ["ui.scout.bet"] = "EL CORREDOR",
        ["ui.scout.betNone"] = "Hoy el corredor no abre libro.",
        ["ui.scout.betPrice"] = "Pones {0} de oro; si se cumple, cobras {1}.",
        ["ui.scout.betFreq.rare"] = "Se cumple rara vez.",
        ["ui.scout.betFreq.sometimes"] = "Se cumple de vez en cuando.",
        ["ui.scout.betFreq.often"] = "Se cumple a menudo.",
        ["ui.scout.betFreq.veryOften"] = "Se cumple casi la mitad de las veces.",
        ["ui.scout.betTake"] = "Apostar",
        ["ui.scout.betWithdraw"] = "Retirar la apuesta",
        ["ui.scout.betTaken"] = "Apuesta hecha: has puesto {0}; si se cumple, cobras {1}.",
        ["ui.scout.betNoGold"] = "No te llega el oro: la apuesta cuesta {0} y llevas {1}.",
        ["ui.scout.start"] = "Confirmar y jugar",
        ["ui.scout.boss"] = "MODIFICADORES DEL JEFE",
        ["ui.scout.bossHidden"] = "el modificador se descubre al llegar aquí, y ya lo has hecho",
        ["ui.scout.starters"] = "TU ONCE",

        // Memoria del rival (F1 §6, ADR 0124): reencuentro contra un clan ya visto, y el par
        // knaveador-víctima más destacado si lo hay (BE-B). Nunca en el nodo de jefe (ScoutScreen lo filtra).
        ["ui.report.nemesisMade"] = "{0}, {1}, mató a {2}: se convierte en tu némesis.",
        ["ui.report.revenge"] = "¡VENGANZA! {0} vengó a {1}: lesionó a {2}, {3}.",
        ["ui.report.revengeSlain"] = "¡VENGANZA! {0} vengó a {1}: mató a {2}, {3}.",
        ["ui.report.revengeGold"] = "+{0} de oro",
        ["ui.map.nemesis"] = "némesis: {0}, {1}",
        ["ui.map.mob"] = "turba: {0}",
        ["ui.scout.nemesis"] = "NÉMESIS · {0}, {1}: mató a {2} en el acto {3}. Hoy juega, y con un nivel más.",
        ["ui.scout.nemesisMany"] = "NÉMESIS · {0}, {1}: mató a {2} en el acto {3} y a {4} más. Hoy juega, y con un nivel más.",
        ["ui.scout.rivalRepeat"] = "{0} · {1}.ª vez · {2}",
        ["ui.scout.rivalRepeatWon"] = "ganaste",
        ["ui.scout.rivalRepeatLost"] = "perdiste",
        ["ui.scout.rivalCreditCausedInjury"] = "tu {0} ha lesionado a su {1}",
        ["ui.scout.rivalCreditCausedDeath"] = "tu {0} ha matado a su {1}",
        ["ui.scout.rivalCreditSufferedInjury"] = "su {1} ha lesionado a tu {0}",
        ["ui.scout.rivalCreditSufferedDeath"] = "su {1} ha matado a tu {0}",

        ["ui.node.clinicTitle"] = "CLÍNICA",
        ["ui.node.clinicBody"] = "cuatro servicios: por pieza a {0} de oro y garantizado, la plantilla entera a tarifa plana, el matasanos a una fracción y sin garantía, o el herrero, que no mata pero puede dejar una prótesis",
        ["ui.node.clinicNone"] = "no hay ningún jugador con lesión grave que tratar",
        ["ui.node.clinicPoor"] = "no te llega el oro: tienes {0} y cuesta {1}",
        ["ui.node.treat"] = "Tratar a {0} ({1} de oro)",
        ["ui.node.treatSquad"] = "Curar a la plantilla · {0} de oro ({1} lesionados, uno a uno serían {2})",
        ["ui.node.treatSquadOne"] = "Curar a la plantilla · {0} de oro (1 lesionado, uno a uno serían {2})",
        ["ui.node.treatedSquad"] = "la clínica cura a los {0} lesionados",
        ["ui.node.treatedSquadOne"] = "la clínica cura al único lesionado",
        ["ui.node.treatRiskyCap"] = "Matasanos · {0} de oro ({1}% no cure, {2}% empeore a grave y lo deje lisiado)",
        ["ui.node.treatRisky"] = "Matasanos · {0} de oro ({1}% de que no cure, {2}% de que empeore)",
        ["ui.node.treatedRisky"] = "el matasanos opera a {0}",
        ["ui.node.treated"] = "{0} vuelve a estar sano",
        ["ui.node.forgeOpen"] = "Herrero · desde {0} de oro",
        ["ui.node.forgeTitle"] = "MESA DEL HERRERO · {0}",
        ["ui.node.forgeCure"] = "{0}% curación: vuelve sano y sin prótesis",
        ["ui.node.forgeImprove"] = "{0}% mejora: sale con una prótesis con ventaja y la etiqueta Chatarra",
        ["ui.node.forgeWorsen"] = "{0}% empeoramiento: sale con una prótesis con desventaja y la etiqueta Chatarra (el herrero nunca mata)",
        ["ui.node.forgeImproveRange"] = "de {0} a {1} en: {2} (según las ranuras libres)",
        ["ui.node.forgeWorsenRange"] = "de {0} a {1} en: {2} (según las ranuras libres)",
        ["ui.node.forgeSlots"] = "ranuras libres: {0}. Una ranura ocupada no admite otra prótesis",
        ["ui.node.forgeAutomaton"] = "una prótesis más y {0} pasa a ser también Autómata (conserva su especie); desde ahí, la próxima lesión grave lo deja lisiado: sin cura ni alineación",
        ["ui.node.clinicCrippled"] = "{0}: lisiado ({1}/{2} prótesis y lesión grave). Ya no tiene cura ni se alinea; sigue en la plantilla y se puede vender como lesión grave",
        ["ui.node.clinicCapWarning"] = "{0}: {1}/{2} prótesis. La próxima lesión grave lo deja lisiado, sin cura",
        ["ui.report.crippledRow"] = "{0} queda lisiado: ya no tiene cura",
        ["ui.node.forgeInvest"] = "Oro extra, hasta {0} (cada uno rinde menos). El botón muestra curación / mejora / empeoramiento:",
        ["ui.node.forgeExtra"] = "+{0} · {1}/{2}/{3}",
        ["ui.node.forgeConfirm"] = "Confirmar · {0} de oro (+{1} extra)",
        ["ui.node.forgeClose"] = "Cerrar la mesa",
        ["ui.node.forgeCured"] = "el herrero cura a {0} sin dejarle nada dentro",
        ["ui.node.forgeImproved"] = "el herrero ha acertado: {0} sale con {1} ({2} {3})",
        ["ui.node.forgeWorsened"] = "el herrero se ha equivocado: {0} sale con {1} ({2} {3})",
        ["ui.node.forgeBecameAutomaton"] = "{0} ya es también un Autómata (y sigue siendo de su especie).",
        ["ui.prosthesis.slot.arm"] = "brazo",
        ["ui.prosthesis.slot.leg"] = "pierna",
        ["ui.prosthesis.slot.eye"] = "ojo",
        ["ui.prosthesis.slot.jaw"] = "mandíbula",
        ["ui.prosthesis.slot.spine"] = "columna",
        ["ui.prosthesis.slot.gut"] = "tripa",
        ["ui.prosthesis.slot.skull"] = "cráneo",
        ["ui.node.trainTitle"] = "ENTRENAMIENTO",
        ["ui.node.trainBody"] = "elige una sesión para hoy; lo que cuesta y lo que da está escrito en cada una",
        ["ui.node.trainOption"] = "{0} — {1}",
        ["ui.node.trainPickTarget"] = "señala a quién",
        ["ui.node.trainPickPosition"] = "elige el puesto de destino",
        ["ui.node.trainTarget"] = "{0} · {1}",
        ["ui.node.trainChosen"] = "{0}",
        ["ui.node.trainChosenOn"] = "le toca a {0}",
        ["ui.node.trainNone"] = "Este nodo ya no tiene ninguna sesión que resolver. Vuelve al mapa cuando quieras.",
        ["ui.node.eventTitle"] = "EVENTO",
        ["ui.node.eventBody"] = "elige una opción; lo que cuesta y lo que da está escrito en cada una",
        ["ui.node.gold"] = "oro: {0}",
        ["ui.node.eventOption"] = "{0} — {1}",
        ["ui.node.eventPickTarget"] = "señala a quién",
        ["ui.node.eventPickSecondTarget"] = "y a un segundo jugador",
        ["ui.node.eventNone"] = "Este nodo ya no tiene ninguna carta que resolver. Vuelve al mapa cuando quieras.",
        ["ui.node.eventTarget"] = "{0} · {1}",
        ["ui.node.eventChosen"] = "{0}",
        ["ui.node.eventChosenOn"] = "le toca a {0}",
        ["ui.node.eventChosenOnTwo"] = "le toca a {0} y a {1}",
        ["ui.node.leave"] = "Salir al mapa",
        ["ui.node.error"] = "no se pudo: {0}",

        ["ui.end.victory"] = "VICTORIA",
        ["ui.end.defeat"] = "DERROTA",
        ["ui.end.victoryBody"] = "el jefe del acto 3 ha caído. La run termina en victoria.",
        ["ui.end.causeBoss"] = "causa: se perdió un partido de jefe",
        ["ui.end.causePlayers"] = "causa: los jugadores disponibles bajaron de {0}",
        ["ui.end.stats"] = "actos superados {0} de {1} · nodos {2} · partidos {3} ganados de {4} · oro {5}",
        ["ui.end.roster"] = "PLANTILLA FINAL",
        ["ui.end.fallen"] = "CAÍDOS",
        ["ui.end.fallenNone"] = "ninguno: la run termina con la plantilla entera viva",
        ["ui.end.fallenLine"] = "{0} · {1} · nivel {2}",
        ["ui.end.again"] = "Otra run",
        ["ui.end.seed"] = "semilla {0} · {1}",

        ["ui.kind.LeagueMatch"] = "partido de liga",
        ["ui.kind.EliteMatch"] = "partido de élite",
        ["ui.kind.Market"] = "mercado",
        ["ui.kind.Clinic"] = "clínica",
        ["ui.kind.Workshop"] = "taller",
        ["ui.kind.Training"] = "entrenamiento",
        ["ui.kind.Event"] = "evento",
        ["ui.kind.Boss"] = "jefe",
        ["ui.difficulty.1"] = "asequible",
        ["ui.difficulty.2"] = "seria",
        ["ui.difficulty.3"] = "dura",
        ["ui.difficulty.4"] = "muy dura",
        ["ui.difficulty.5"] = "letal",
        ["ui.risk.percent"] = "{0},{1}%",
        ["ui.input.mouseOnly"] = "RATÓN  clic: elegir · clic en una ficha: expandirla",
        ["ui.input.padPending"] = "MANDO  pendiente en esta pantalla: la navegación con mando está hecha en Equipo",

        // --- partido, informe, recompensa y mercado (docs/ui-run-minima.md) ---
        ["ui.card.rarity.Uncommon"] = "poco común",

        ["ui.match.title"] = "PARTIDO",
        ["ui.match.subtitle"] = "{0} · dificultad {1}/5 · acto {2} · árbitro {3}",
        ["ui.match.log"] = "LOG DEL PARTIDO",
        ["ui.match.highlights"] = "SUCESOS CLAVE",
        ["ui.match.hint"] = "el partido ya está resuelto: esto es lo que pasó. Pausa, retrocede y vuelve a ver la jugada que quieras.",
        ["ui.match.minute"] = "minuto {0}",
        ["ui.match.kickoff"] = "antes del saque",
        ["ui.match.golden"] = "prórroga de turba: el siguiente gol gana",
        ["ui.match.forfeit"] = "incomparecencia: un equipo se quedó sin jugadores",
        ["ui.match.final"] = "FINAL · {0}",
        ["ui.match.won"] = "victoria",
        ["ui.match.lost"] = "derrota",
        ["ui.match.progress"] = "{0} de {1} sucesos",
        ["ui.match.pause"] = "Pausa",
        ["ui.match.resume"] = "Seguir",
        ["ui.match.speed"] = "Velocidad x{0}",
        ["ui.match.all"] = "Mostrar todo",
        ["ui.match.report"] = "Ir al informe",
        ["ui.match.cancelled"] = "anulado por un perk",
        ["ui.match.none"] = "no hay ningún partido que enseñar",
        ["ui.match.highlightsNone"] = "todavía no ha pasado nada digno de mención",

        // --- campo del partido (traza de posiciones, MatchTrace) ---
        ["ui.match.pitch"] = "CAMPO",
        ["ui.match.clock"] = "minuto {0} · tick {1} de {2} · {3}",
        ["ui.match.stepBack"] = "◀ tick",
        ["ui.match.stepForward"] = "tick ▶",
        ["ui.match.end"] = "Al final",
        ["ui.match.zoneOn"] = "Correa: sí",
        ["ui.match.zoneOff"] = "Correa: no",
        ["ui.match.selected"] = "{0} · {1} · dorsal {2} · {3}",
        ["ui.match.selectHint"] = "clic en una ficha para seguirla y ver su correa",
        ["ui.match.legendOwn"] = "tu equipo",
        ["ui.match.legendRival"] = "rival",
        ["ui.match.legendBall"] = "balón",
        ["ui.match.legendCarrier"] = "lo lleva",
        ["ui.match.legendZone"] = "correa del elegido",
        ["ui.match.legendMark"] = "marca a (asignado)",
        ["ui.match.legendMarking"] = "yendo a por él",
        ["ui.match.markOn"] = "Marcaje: sí",
        ["ui.match.markOff"] = "Marcaje: no",

        // ADR 0102: los dos interruptores de la prueba de geometría en 3D. Siguen el patrón de "Correa:" y
        // "Marcaje:" — el botón dice el estado en el que está, no el que se pide.
        ["ui.match.view2d"] = "3D: no",
        ["ui.match.view3d"] = "3D: sí",
        ["ui.match.bwOff"] = "B/N: no",
        ["ui.match.bwOn"] = "B/N: sí",
        ["ui.match.doing"] = "quiere {0}",
        ["ui.match.marking"] = "marca a {0} (dorsal {1})",
        ["ui.match.markAssigned"] = "marca al {0}",
        ["ui.match.noAction"] = "todavía no ha decidido nada",
        ["ui.match.noTrace"] = "este partido se reprodujo sin traza: no hay campo que enseñar",

        ["ui.phase.Kickoff"] = "saque",
        ["ui.phase.OpenPlay"] = "juego",
        ["ui.phase.Restart"] = "reanudación",
        ["ui.phase.Penalty"] = "penalti",
        ["ui.phase.RegulationEnd"] = "fin del reglamentario",
        ["ui.phase.MobGoldenGoal"] = "turba: gol de oro",
        ["ui.phase.Finished"] = "final",

        ["ui.pstate.Positioning"] = "coloca",
        ["ui.pstate.Chasing"] = "persigue",
        ["ui.pstate.Dribbling"] = "regatea",
        ["ui.pstate.Passing"] = "pasa",
        ["ui.pstate.Shooting"] = "tira",
        ["ui.pstate.Tackling"] = "entra",
        ["ui.pstate.Blocking"] = "carga",
        ["ui.pstate.KnockedDown"] = "derribado",
        ["ui.pstate.Injured"] = "lesionado",
        ["ui.pstate.Celebrating"] = "celebra",
        ["ui.pstate.SentOff"] = "expulsado",

        // Las trece acciones de la tabla de utilidad (RT-098). Se leen detrás de "quiere ...", así que van
        // en infinitivo: es lo que el jugador está intentando hacer, no lo que ha conseguido.
        ["ui.paction.ChaseBall"] = "ir a por el balón",
        ["ui.paction.MarkOpponent"] = "marcar a un rival",
        ["ui.paction.OfferSupport"] = "ofrecerse para el pase",
        ["ui.paction.CoverSpace"] = "cubrir su espacio",
        ["ui.paction.Dribble"] = "regatear",
        ["ui.paction.Shoot"] = "tirar",
        ["ui.paction.Tackle"] = "entrar a por el balón",
        ["ui.paction.Retreat"] = "replegarse",
        ["ui.paction.FindSpace"] = "buscar un hueco",
        ["ui.paction.PressCarrier"] = "presionar al que lleva el balón",
        ["ui.paction.ShortPass"] = "dar un pase corto",
        ["ui.paction.LongPass"] = "abrir el juego en largo",
        ["ui.paction.Block"] = "cargar contra un rival",

        ["ui.match.subTitle"] = "SUSTITUCIÓN",
        ["ui.match.subInjury"] = "{0} se ha lesionado y no puede seguir. Elige quién entra en su casilla:",
        ["ui.match.subDeath"] = "{0} ha muerto en el campo. Elige quién entra en su casilla:",
        ["ui.match.subCandidate"] = "{0} · {1} · {2}",
        ["ui.match.subHint"] = "la sustitución es obligatoria mientras haya banquillo; un lesionado leve que salta al campo arriesga la vida",
        ["ui.ev.Substitution"] = "{0} entra por {1}",
        ["ui.ev.MatchStart"] = "empieza el partido",
        ["ui.ev.MatchEnd"] = "final del partido",
        ["ui.ev.MobStart"] = "la turba invade el campo",
        ["ui.ev.RefereeLeaves"] = "el árbitro abandona el campo",
        ["ui.ev.PassCompleted"] = "{0} encuentra a {1}",
        ["ui.ev.PassFailed"] = "{0} pierde el pase",
        ["ui.ev.DribbleWon"] = "{0} regatea a {1}",
        ["ui.ev.DribbleLost"] = "{0} pierde el balón ante {1}",
        ["ui.ev.AerialDuel"] = "{0} salta contra {1}",
        ["ui.ev.Tackle"] = "{0} entra a {1}",
        ["ui.ev.Recovery"] = "{0} recupera el balón",
        ["ui.ev.Shot"] = "{0} dispara",
        ["ui.ev.Goal"] = "GOL de {0}",
        ["ui.ev.Save"] = "{0} para el tiro de {1}",
        ["ui.ev.ShotBlocked"] = "{0} bloquea el disparo de {1}",
        // ADR 0135 paso 2b y ADR 0136. Faltaban las dos: UiText.Get devuelve la CLAVE cuando no encuentra
        // la entrada, así que un tiro al palo se narraba como el literal "ui.ev.ShotPost".
        ["ui.ev.ShotPost"] = "{0} estrella el balón en la madera",
        ["ui.ev.Cross"] = "{0} pone el centro para {1}",
        ["ui.ev.Foul"] = "{0} hace falta a {1}",
        ["ui.ev.Card"] = "{0} ve tarjeta",
        ["ui.ev.Injury"] = "{0} cae lesionado",
        ["ui.ev.Death"] = "{0} MUERE en el campo",
        ["ui.ev.Substitution"] = "{0} entra por {1}",
        ["ui.ev.ConsumableUsed"] = "{0} usa un consumible",
        ["ui.ev.PassAttempted"] = "{0} intenta el pase a {1}",
        ["ui.ev.DribbleAttempted"] = "{0} encara a {1}",
        ["ui.ev.PlayStart"] = "arranca la jugada",
        ["ui.ev.PlayEnd"] = "se acaba la jugada",

        ["ui.report.title"] = "INFORME",
        ["ui.report.subtitle"] = "{0} {1}-{2} {3} · {4} · {5} minutos",
        ["ui.report.victory"] = "VICTORIA",
        ["ui.report.defeat"] = "DERROTA",
        ["ui.report.perks"] = "PERKS ACTIVADOS",
        ["ui.report.perksNone"] = "ningún perk tuyo llegó a activarse en este partido",
        ["ui.report.perkRow"] = "{0} · lo lleva {1}",
        ["ui.report.activations"] = "{0} activaciones",
        ["ui.report.activationOne"] = "1 activación",
        ["ui.report.contribution"] = "en sus activaciones: {0}",
        ["ui.report.contribNone"] = "en sus activaciones no cayó ningún gol, lesión ni recuperación",
        ["ui.report.cGoals"] = "{0} goles",
        ["ui.report.cGoal"] = "1 gol",
        ["ui.report.cInjuries"] = "{0} lesiones causadas",
        ["ui.report.cInjury"] = "1 lesión causada",
        ["ui.report.cRecoveries"] = "{0} recuperaciones",
        ["ui.report.cRecovery"] = "1 recuperación",
        ["ui.report.cSaves"] = "{0} paradas",
        ["ui.report.cSave"] = "1 parada",
        ["ui.report.cCancels"] = "{0} sucesos anulados",
        ["ui.report.cCancel"] = "1 suceso anulado",
        ["ui.report.items"] = "EQUIPAMIENTO",
        ["ui.report.itemsNone"] = "nadie salió al campo con objeto",
        ["ui.report.itemRow"] = "{0} · lo lleva {1}",
        ["ui.report.itemRestricted"] = "no le aporta nada: no es de su raza",
        ["ui.report.casualties"] = "BAJAS",
        ["ui.report.casualtiesNone"] = "sin bajas: la plantilla sale entera",
        ["ui.report.deathRow"] = "MUERE {0} · minuto {1}",
        ["ui.report.injuryRow"] = "{0} · {1} · minuto {2}",
        ["ui.report.cause"] = "por {0}",
        ["ui.report.relic"] = "{0} deja {1} en el cofre",
        ["ui.report.cards"] = "TARJETAS",
        ["ui.report.cardsNone"] = "el árbitro no sacó ninguna",
        ["ui.report.cardRow"] = "{0} · {1} · minuto {2}",
        ["ui.report.cardYellow"] = "amarilla",
        ["ui.report.cardRed"] = "roja",
        ["ui.report.sideOwn"] = "tuya",
        ["ui.report.sideRival"] = "del rival",
        ["ui.report.gold"] = "ORO GANADO",
        ["ui.report.goldNone"] = "perder no paga",
        ["ui.report.goldBase"] = "base del acto {0}",
        ["ui.report.goldDifficulty"] = "dificultad {0}/5 (x{1}%)",
        ["ui.report.goldNode"] = "{0} (+{1}%)",
        ["ui.report.bet"] = "LA APUESTA",
        ["ui.report.betWon"] = "Cobras {0} de oro: {1}",
        ["ui.report.betLost"] = "Pierdes {0} de oro: {1}",
        ["ui.report.goldTotal"] = "TOTAL",
        ["ui.report.goldNow"] = "oro de la run: {0}",
        ["ui.report.loot"] = "botín de liga: {0}, al cofre",
        ["ui.report.referee"] = "ÁRBITRO",
        ["ui.report.refereeBias"] = "criterio {0} al empezar, {1} al terminar",
        ["ui.report.refereeFouls"] = "faltas señaladas: {0} tuyas, {1} del rival",
        ["ui.report.refereeCards"] = "tarjetas: {0} tuyas, {1} del rival",
        ["ui.report.refereeUnseen"] = "faltas no señaladas: {0} tuyas, {1} del rival",
        ["ui.report.stats"] = "ESTADÍSTICAS",
        ["ui.report.statsHead"] = "gol asi ent fal les",
        ["ui.report.statsNone"] = "nadie pisó el campo",
        ["ui.report.nicknameEarnedRow"] = "gana «{0}»",
        ["ui.report.nicknameUpgradedRow"] = "pasa de «{1}» a «{0}»",
        ["ui.report.statsMoreOne"] = "y 1 jugador más",
        ["ui.report.statsMore"] = "y {0} jugadores más",
        ["ui.gazette.obituariesMoreOne"] = "… y 1 esquela más, en la plantilla final",
        ["ui.gazette.obituariesMore"] = "… y {0} esquelas más, en la plantilla final",
        ["ui.report.continue"] = "Continuar",
        ["ui.report.none"] = "todavía no se ha jugado ningún partido",
        ["ui.report.deaths"] = "{0} MUERTOS",
        ["ui.report.death"] = "1 MUERTO",


        ["ui.reward.title"] = "RECOMPENSA",
        ["ui.reward.subtitle"] = "{0} · elección {1} de {2} · {3} de oro",
        ["ui.reward.badgePerk"] = "PERK",
        ["ui.reward.badgePlayer"] = "JUGADOR",
        ["ui.reward.badgeItem"] = "OBJETO",
        ["ui.reward.choose"] = "Elegir",
        ["ui.reward.assign"] = "Elegir y asignar",
        ["ui.reward.noCarrierNeeded"] = "entra en la plantilla: no hay a quién asignárselo",
        ["ui.reward.confirm"] = "Dárselo a {0}",
        ["ui.reward.decline"] = "Rechazar la recompensa",
        ["ui.reward.declineHint"] = "con los perks irreversibles y los slots contados, quedarse con la menos mala puede ser peor que no quedarse con nada",
        ["ui.reward.reroll"] = "Repetir la tirada ({0} de oro)",
        ["ui.reward.rerollUsed"] = "el reroll de este nodo ya se ha usado: uno por nodo",
        ["ui.reward.rerollPoor"] = "repetir cuesta {0} de oro y tienes {1}",
        ["ui.reward.carrier"] = "A QUIÉN SE LO DAS",
        ["ui.reward.carrierPerk"] = "un perk asignado NO SE PUEDE RETIRAR ni transferir: la decisión dura toda la run.",
        ["ui.reward.carrierItem"] = "cada jugador lleva un objeto y solo uno: el que tuviera vuelve al almacén.",
        ["ui.reward.carrierRow"] = "{0} · {1} · nivel {2} · {3} · {4}",
        ["ui.reward.slots"] = "{0} slots libres",
        ["ui.reward.slot"] = "1 slot libre",
        ["ui.reward.carrierHasItem"] = "lleva {0}",
        ["ui.reward.carrierNoItem"] = "sin objeto",
        ["ui.reward.blockRoster"] = "plantilla llena ({0} de {1}): hay que rechazar o hacer sitio",
        ["ui.reward.blockCarrier"] = "nadie de tu plantilla puede llevarlo",
        ["ui.reward.none"] = "no hay ninguna recompensa que elegir",
        ["ui.reward.pick"] = "elige un artículo para ver a quién puedes dárselo",
        ["ui.reward.optionsLeague"] = "un partido de liga ofrece una elección entre dos",
        ["ui.reward.optionsElite"] = "un partido de élite ofrece una entre tres, con mejor rareza",
        ["ui.reward.optionsBoss"] = "el jefe ofrece dos elecciones entre tres y cura las lesiones leves",
        ["ui.reward.error"] = "no se pudo: {0}",

        ["ui.market.title"] = "MERCADO",
        ["ui.market.subtitle"] = "acto {0} · {1} de oro · plantilla {2} de {3} · la única tienda del juego, y no se renueva",
        ["ui.market.players"] = "JUGADORES",
        ["ui.market.perks"] = "PERKS",
        ["ui.market.items"] = "EQUIPAMIENTO",
        ["ui.market.consumables"] = "CONSUMIBLES",
        ["ui.market.sell"] = "VENDER JUGADORES",
        ["ui.market.action"] = "ARTÍCULO ELEGIDO",
        ["ui.market.buy"] = "Comprar ({0} de oro)",
        ["ui.market.take"] = "Fichar gratis",
        ["ui.market.hire"] = "Fichar (salario {0} por partido)",
        ["ui.market.sellButton"] = "Vender a {0} por {1} de oro",
        ["ui.market.badgeYouth"] = "CANT",
        ["ui.market.badgeMercenary"] = "MERC",
        ["ui.market.badgePlayer"] = "FICH",
        ["ui.market.badgePerk"] = "PERK",
        ["ui.market.badgeItem"] = "OBJ",
        ["ui.market.badgeConsumable"] = "CONS",
        ["ui.market.youthHint"] = "CANTERANO GRATIS: malo hoy y con un 33% más de experiencia; el crack del acto 3 sale de aquí",
        ["ui.market.mercenaryHint"] = "MERCENARIO: sin coste de fichaje, {0} de salario por partido, y se marcha tras 3 partidos en el banquillo",
        ["ui.market.free"] = "gratis",
        ["ui.market.price"] = "{0} oro",
        ["ui.market.wage"] = "salario {0}",
        ["ui.market.cursedHint"] = "MALDITO: sube el doble y baja algo a cambio",
        ["ui.market.fragileHint"] = "FRÁGIL: {0}% de romperse al terminar cada partido",
        ["ui.market.restrictedHint"] = "EXCLUSIVO DE RAZA: no aporta nada a un portador que no sea {0}",
        ["ui.market.carrier"] = "QUIÉN LO LLEVA",
        ["ui.market.nothing"] = "elige un artículo de cualquiera de las cuatro columnas",
        ["ui.market.poor"] = "no te llega el oro: cuesta {0} y tienes {1}",
        ["ui.market.rosterFull"] = "plantilla llena ({0} de {1}): vende a alguien o compra un hueco en el mercado",
        ["ui.market.noCarrier"] = "nadie de tu plantilla puede llevarlo",
        ["ui.market.consumableFull"] = "tus {0} huecos de consumible están llenos: usa o descarta uno en Equipo antes de comprar otro",
        ["ui.market.consumableCarried"] = "ya lo llevas en uno de tus huecos",
        ["ui.market.slot"] = "Ampliar plantilla · {0} de oro ({1}/{2})",
        ["ui.market.slotFull"] = "plantilla en su techo: no quedan huecos que inscribir",
        ["ui.market.leave"] = "Salir al mapa",
        ["ui.market.sellWarn"] = "quedan {0} disponibles: vender a uno más termina la run",
        ["ui.market.sellRow"] = "{0} · nivel {1} · perks {2}",
        ["ui.market.empty"] = "sin artículos",
        ["ui.market.none"] = "no hay ningún mercado abierto",
        ["ui.market.error"] = "no se pudo: {0}",
        ["ui.input.mouseMatch"] = "RATÓN  clic en una ficha: seguirla · clic o arrastre en la barra: moverse por el partido · botones: pausa, velocidad y tick a tick",
        ["ui.input.padMatch"] = "MANDO  A: pausa y continuar · izquierda/derecha: un tick atrás o adelante · B: ir al informe · F3: retransmisión",
        ["ui.input.mouseReport"] = "RATÓN  rueda: recorrer los perks activados · clic en Continuar para seguir",
        ["ui.input.mouseReward"] = "RATÓN  clic en una opción: elegirla · clic en un jugador: dársela",
        // Encargo mercado-arrastrar (20 sep 2026, UI-001/UI-006): el desplegable de "a quién se lo doy"
        // desaparece, así que la ayuda de entrada describe el arrastre, no un clic. Es el mismo patrón
        // mouseX/padX que ya usan partido (mouseMatch/padMatch): antes solo había mouseMarket, porque el
        // mando no estaba implementado en esta pantalla (ui.input.padPending); ahora lo está.
        ["ui.input.mouseMarket"] =
            "RATÓN  arrastra la carta de un perk, un objeto o un consumible hasta el hueco de un jugador o "
            + "los huecos de consumible; suelta fuera para cancelar sin coste. Jugadores, venta y ampliar plantilla se compran con un clic.",
        ["ui.input.padMarket"] =
            "MANDO  A coge la carta señalada, la cruceta mueve el cursor por la plantilla y los huecos de consumible, A suelta, "
            + "B cancela. Fichar jugadores, vender y ampliar plantilla siguen siendo solo de ratón.",
        ["ui.market.sellNobody"] = "elige a quién vender en la lista",

        // Encargo mercado-arrastrar (20 sep 2026, UI-001/UI-006/UI-010): perk, objeto y consumible se
        // compran arrastrando su carta hasta el hueco de un jugador o los huecos de consumible, en vez de con
        // el desplegable "QUIÉN LO LLEVA" (ui.market.carrier, ya sin uso).
        ["ui.market.bagTitle"] = "HUECOS DE CONSUMIBLE {0}/{1}",
        ["ui.market.bagHint"] = "suelta aquí uno: entra ya equipado",
        ["ui.market.bagHintFull"] = "llenos: usa o descarta uno en Equipo",
        ["ui.market.detailNone"] = "pasa el ratón o el cursor por un artículo para verlo aquí",
        ["ui.market.holding"] = "SUJETANDO:",
        ["ui.market.dragToPlayer"] = "arrastra la carta hasta el hueco de un jugador de la plantilla",
        ["ui.market.dragToBag"] = "arrastra la carta hasta los huecos de consumible",
        ["ui.market.reasonPerkCarrier"] = "{0} no puede llevar este perk: sin hueco libre, ya lo lleva, o no cumple sus etiquetas",
        ["ui.market.reasonItemCarrier"] = "{0} no puede llevar este objeto",
        ["ui.market.reasonWrongPlayer"] = "esto se suelta sobre los huecos de consumible, no sobre un jugador",
        ["ui.market.reasonWrongBag"] = "esto se suelta sobre un jugador de la plantilla, no sobre los huecos de consumible",
        ["ui.market.reasonOk"] = "suelta aquí para comprarlo y llevarlo ya equipado",

        // --- sección de consumibles de Equipo (CAT-B, RF-080..085) ---
        ["ui.team.consumableButton"] = "Consumibles",
        ["ui.team.consumableTitle"] = "CONSUMIBLES",
        ["ui.team.consumableError"] = "no se pudo: {0}",
        ["ui.team.consumableInputMouse"] = "RATÓN  clic en un consumible: verlo · clic en Hacer manual / Otro disparador / Descartar: aplicarlo",
        ["ui.team.consumableFamilyMedical"] = "médico",
        ["ui.team.consumableFamilyTactical"] = "táctico",
        ["ui.team.consumableFamilyDirty"] = "sucio",
        ["ui.team.consumableFamilySupernatural"] = "sobrenatural",
        ["ui.team.consumableBadgeMedical"] = "MED",
        ["ui.team.consumableBadgeTactical"] = "TAC",
        ["ui.team.consumableBadgeDirty"] = "SUC",
        ["ui.team.consumableBadgeSupernatural"] = "SOB",
        ["ui.team.consumableTriggerScoreBehind"] = "vas por debajo en el marcador",
        ["ui.team.consumableTriggerScoreTied"] = "el marcador está empatado",
        ["ui.team.consumableTriggerLastSeconds"] = "quedan los últimos 20 segundos",
        ["ui.team.consumableTriggerMobStart"] = "entra la turba",
        ["ui.team.consumableTriggerOwnInjury"] = "sufres una lesión",
        ["ui.team.consumableTriggerOwnRedCard"] = "ves una tarjeta roja",

        // --- cofre de Equipo (ADR 0161 §3): almacén, equipar/guardar/pasar sobre el jugador señalado ---
        ["ui.team.chestButton"] = "Cofre",
        ["ui.team.chestTitle"] = "COFRE",
        // Distintivo corto a propósito (OptionCard reserva 42 px fijos antes del título en modo pequeño,
        // Game/Ui/OptionCard.cs: "OBJETO" de ui.reward.badgeItem monta sobre el título en esa anchura).
        ["ui.team.chestBadge"] = "OBJ",
        ["ui.team.chestHint"] = "botín de liga, reliquias y equipo heredado de un muerto: nada cuesta oro",
        ["ui.team.chestAction"] = "ACCIÓN",
        ["ui.team.chestEmpty"] = "el cofre está vacío: gana una liga o pierde a alguien con historia",
        ["ui.team.chestCopies"] = "{0} en el cofre",
        ["ui.team.chestNoPlayer"] = "señala a un jugador de la plantilla para equipar, guardar o pasar su objeto",
        ["ui.team.chestPlayer"] = "{0}",
        ["ui.team.chestPlayerEmpty"] = "no lleva ningún objeto",
        ["ui.team.chestPlayerHas"] = "lleva puesto: {0}",
        ["ui.team.chestEquip"] = "Equipar",
        ["ui.team.chestStore"] = "Guardar en el cofre",
        ["ui.team.chestPass"] = "Pasar a otro",
        ["ui.team.chestPassHint"] = "a quién se lo pasas (si ya lleva uno, el suyo vuelve al cofre)",
        ["ui.team.chestError"] = "no se pudo hacer ese cambio con el objeto",
        ["ui.team.chestInputMouse"] = "RATÓN  señala a un jugador en la plantilla · clic en un objeto del cofre: elegirlo · clic en Equipar/Guardar/Pasar: aplicarlo",

        // --- retransmisión de partido, «voz de pregón» (ADR 0119, ADR 0120; docs/ui/README.md) ---
        ["ui.pregon.speed.x1"] = "x1",
        ["ui.pregon.speed.x4"] = "x4",
        ["ui.pregon.speed.x16"] = "x16",
        ["ui.pregon.speed.pause"] = "‖",
        ["ui.pregon.order.defensive"] = "Defensa",
        ["ui.pregon.order.neutral"] = "Neutro",
        ["ui.pregon.order.offensive"] = "Ataque",
        ["ui.pregon.strip.subtitle"] = "{0} · {1}",
        ["ui.pregon.strip.perks"] = "{0}  ✦{1}",
        ["ui.pregon.bench"] = "Banquillo {0}",
        ["ui.pregon.board.residue"] = "▮{0} · ✚{1}",
        // BR-A, ADR 0183: al volver de un partido a medias lo ya visto no se puede volver a decidir.
        ["ui.match.replayLocked"] = "Partido retomado: ya lo habías visto hasta el minuto {0}. No se puede decidir hasta entonces.",
        ["ui.match.replayLockedAll"] = "Partido retomado: ya lo habías visto entero. No se puede decidir; sólo verlo.",
        // Criterio del árbitro, SIEMPRE visible en el tablero (RF-062, ADR 0158 §6): el medidor de
        // BroadcastBoard.DrawCriterionMeter lee esta etiqueta con el signo ya puesto (UiText.Signed).
        ["ui.pregon.board.bias"] = "CRITERIO {0}",
        // El pergamino sobre la cabeza del árbitro en el campo 3D (ADR 0158 §6, RF-061, RF-119):
        // MatchPitchView3D.DrawRefereeGesture, falta pitada / falta no señalada.
        ["ui.pregon.referee.foul"] = "¡Falta!",
        ["ui.pregon.referee.unseen"] = "¿?",
        ["ui.pregon.stamp.foul"] = "Falta",
        ["ui.pregon.stamp.unseen"] = "No lo ha visto",
        ["ui.pregon.banner.said"] = "Se hace saber",
        ["ui.pregon.edict.said"] = "Se hace saber",
        ["ui.pregon.edict.deathOf"] = "el fallecimiento de",
        ["ui.pregon.record.title"] = "Fin del encuentro",
        ["ui.pregon.record.winner"] = "{0} vence a {1}",
        ["ui.pregon.tray.caption"] = "Sustitución · partido en pausa",
        ["ui.pregon.tray.confirm"] = "Confirmar",
        ["ui.pregon.tray.arrow"] = "→",
        ["ui.pregon.tray.hint"] = "◀ ▶ elegir · A / clic confirmar",
        ["ui.pregon.tray.outLabel"] = "Sale · {0}",
        ["ui.pregon.tray.outSub"] = "{0} · casilla {1} · {2}",
        ["ui.pregon.tray.candidateSub"] = "{0} · {1}",
        ["ui.pregon.tray.candidateSubRecommended"] = "{0} · {1} · {2}",
        ["ui.pregon.tray.recommended"] = "recomendado",

        // ADR 0171, la tirada del destino. {0} = quien tira, {1} = quien se la juega, {2} = el porcentaje real
        // (viene del motor, la pantalla no lo calcula). Humor de pregonero, sin nombres internos.
        ["ui.pregon.fate.header"] = "Se hace saber: los dados del destino",
        ["ui.pregon.fate.severe"] = "{0} ha dejado tocado a {1}, y hay un {2} % de que sea grave",
        ["ui.pregon.fate.severeNobody"] = "{1} está tocado, y hay un {2} % de que sea grave",
        ["ui.pregon.fate.death"] = "{0} tiene un {2} % de mandar a {1} al otro barrio",
        ["ui.pregon.fate.deathNobody"] = "{1} tiene un {2} % de irse al otro barrio",
        ["ui.pregon.fate.savedSevere"] = "Sólo un rasguño: se libra de la grave por los pelos",
        ["ui.pregon.fate.savedDeath"] = "¡SE SALVA! Por los pelos",
        ["ui.pregon.fate.diceWanted"] = "los dados lo han querido",
        ["ui.pregon.turba.header"] = "Se hace saber: el árbitro abandona el campo",
        ["ui.pregon.turba.body"] = "¡A la turba! · el próximo gol gana",
        ["ui.pregon.turba.bodyTyped"] = "¡A la turba! · {0} · el próximo gol gana",
        ["ui.pregon.shout.untilEnd"] = "{0} · hasta el final",

        // BA-H, RF-082/085: anuncio del consumible usado (banda sin congelar, igual que la turba) y el
        // rótulo del botón del tablero una vez gastado.
        ["ui.pregon.consumable.header"] = "Se hace saber: {0} usa {1}",
        ["ui.pregon.consumable.body"] = "el efecto se nota en el campo",
        ["ui.pregon.consumable.usedLabel"] = "{0} · usado",
        ["ui.pregon.shout.active"] = "{0} · {1} s",

        // --- retransmisión: sellos N1/N2 y voces altas N3/N4 del director (ADR 0119/0120) ---
        ["ui.pregon.stamp.yellow"] = "Amarilla",
        ["ui.pregon.stamp.minorInjury"] = "Tocado",
        ["ui.pregon.stamp.consumable"] = "Consumible",
        ["ui.pregon.stamp.cancelled"] = "Anulado",
        ["ui.pregon.stamp.substitution"] = "Cambio",
        ["ui.pregon.banner.kickoffTitle"] = "Comienza el partido",
        ["ui.pregon.banner.kickoffNemesis"] = "Némesis en el campo: {0}, {1}",
        ["ui.pregon.banner.kickoffBody"] = "{0} contra {1}",
        ["ui.pregon.banner.goalTitle"] = "Gol",
        ["ui.pregon.banner.goalBody"] = "de {0}, al minuto {1}",
        ["ui.pregon.banner.goalFooter"] = "¡Viva {0}!",
        ["ui.pregon.banner.redTitle"] = "Expulsado",
        ["ui.pregon.banner.redBody"] = "{0}, de {1}",
        ["ui.pregon.banner.redFooter"] = "Juegan con {0}",
        ["ui.pregon.banner.injuryTitle"] = "Herido",
        ["ui.pregon.banner.injuryBody"] = "{0}, {1}",
        ["ui.pregon.banner.injuryFooter"] = "Lesión grave · sale del campo",
        ["ui.pregon.edict.body"] = "{0}, al minuto {1}",
        ["ui.pregon.edict.bodyWithCause"] = "{0}, al minuto {1}; rematado por «{2}»",
        ["ui.pregon.record.hint"] = "Intro para ver el informe",
        ["ui.pregon.tray.outState.death"] = "muerto",
        ["ui.pregon.tray.outState.injury"] = "lesionado",
        // ADR 0134: la bandeja distingue leve de grave porque de eso depende que quepa «que siga jugando».
        ["ui.pregon.tray.outState.injuryMinor"] = "tocado",
        ["ui.pregon.tray.outState.injurySevere"] = "lesión grave",
        ["ui.pregon.tray.decline"] = "Que se quede el hueco",
        // Los subtítulos de la bandeja caben en ~24 caracteres: con cinco respuestas la fila reparte el
        // ancho y cada casilla baja a ~135 px (medido en `pregon-bandeja.png`, 23 sep 2026, donde la
        // primera versión cortaba en «…y no expon» y en «−15» sin el «%»).
        ["ui.pregon.tray.declineSub"] = "juegas con uno menos",
        ["ui.pregon.tray.playOn"] = "Que siga jugando",
        ["ui.pregon.tray.playOnSub"] = "se queda tocado: −15 %",
        ["ui.pregon.tray.playOnSubImmune"] = "no la acusa: entero",
        // La condición es parte de la frase, a propósito: este número NO es el del Ojeo («puede morir en
        // este partido»), que reparte el riesgo por el once. Este dice qué pasa SI le entran (ADR 0134 C).
        ["ui.pregon.tray.candidateRisk"] = "si le entran, muere: {0}",

        // --- Equipo con el lenguaje de Knavall (ADR 0162): cabecera, pestañas y carteles de ayuda. Los
        // carteles dicen QUÉ HACE algo en el juego, en una o dos frases; nunca cómo está implementado. ---
        ["ui.kn.headerCount"] = "{0} BESTIAS EN NÓMINA",
        ["ui.kn.tab.roster"] = "Plantilla",
        ["ui.kn.tab.lineup"] = "Alineación",
        ["ui.kn.tab.consumables"] = "Consumibles",
        ["ui.kn.tab.chest"] = "Cofre",
        ["ui.kn.tab.rosterTip"] = "La ficha de cada jugador, lo que lleva puesto y el cofre del club.",
        ["ui.kn.tab.lineupTip"] = "Coloca a los siete titulares en el campo. Q / E o los gatillos cambian de pestaña.",
        ["ui.kn.tab.consumablesTip"] = "Los dos huecos que llevas al partido.",
        ["ui.kn.tab.chestTip"] = "Los objetos sueltos del club, a la vista y en grande.",
        ["ui.kn.back"] = "Volver",
        ["ui.kn.backTip"] = "Sales de Equipo. Todo lo que has cambiado ya está guardado.",
        ["ui.kn.starters"] = "Titulares",
        ["ui.kn.bench"] = "Suplentes",
        ["ui.kn.starter"] = "Titular",
        ["ui.kn.benchStamp"] = "Suplente",
        ["ui.kn.level"] = "Nivel {0}",
        ["ui.kn.traits"] = "Rasgos",
        ["ui.kn.prostheses"] = "Prótesis",
        ["ui.kn.prosthesisCap"] = "{0}/{1} prótesis: la próxima lesión grave lo deja lisiado",
        ["ui.kn.crippled"] = "Lisiado ({0}/{1} prótesis): sin cura y sin alinear",
        ["ui.kn.perks"] = "Perks",
        ["ui.kn.item"] = "Objeto equipado",
        ["ui.kn.noItem"] = "Va a pelo",
        ["ui.kn.noItemHint"] = "Elige un objeto del cofre y pulsa EQUIPAR.",
        ["ui.kn.equip"] = "Equipar",
        ["ui.kn.store"] = "Guardar\nen el cofre",
        ["ui.kn.pass"] = "Pasar a otro",
        ["ui.kn.passTo"] = "¿A quién se lo pasas?",
        ["ui.kn.cancel"] = "Cancelar",
        ["ui.kn.chest"] = "Cofre",
        ["ui.kn.chestCount"] = "{0} en el cofre",
        ["ui.kn.chestEmpty"] = "Vacío. Gana una liga o pierde a alguien con historia.",
        ["ui.kn.consumables"] = "Consumibles",
        ["ui.kn.consumablesCount"] = "{0} de {1} huecos",
        ["ui.kn.consumablesCountShort"] = "{0}/{1}",
        ["ui.kn.equipped"] = "Al partido",
        ["ui.kn.freeSlot"] = "Hueco libre",
        ["ui.load.lostConsumables"] = "Esta partida guardada llevaba más consumibles de los que caben en los dos huecos. Se han quedado fuera: {0}.",
        ["ui.kn.discardSure"] = "¿Seguro? Descartar",
        ["ui.kn.tip.discardSure"] = "Pulsa otra vez para tirarlo. Elegir otra cosa lo cancela.",
        ["ui.node.eventNoSlot"] = "no tienes hueco libre",
        ["ui.kn.discard"] = "Descartar",
        ["ui.kn.tip.discardConsumable"] = "Lo tira y libera el hueco. No vuelve: para llevar otro hay que comprarlo.",
        ["ui.kn.makeConditional"] = "Que salte solo",
        ["ui.kn.changeTrigger"] = "Otro disparador",
        ["ui.kn.slotsHow"] = "Cómo funcionan",
        ["ui.kn.slotsBuy"] = "Se compran en el mercado y salen ya equipados. Sin un hueco libre no se puede comprar otro.",
        ["ui.kn.slotsConditional"] = "Condicional: salta solo cuando pase lo que le digas. Se elige con «Que salte solo».",
        ["ui.kn.slotsKeep"] = "Lo que no uses se queda en su hueco para el partido siguiente.",
        ["ui.kn.relic"] = "Reliquia",
        ["ui.kn.nobody"] = "Señala a un jugador de la plantilla",
        ["ui.kn.for"] = "Para",
        ["ui.kn.wears"] = "Lleva puesto",
        ["ui.kn.selectedItem"] = "Elegido del cofre",
        ["ui.kn.pickItem"] = "Elige un objeto del cofre",
        ["ui.kn.moving"] = "Moviendo",
        ["ui.kn.lineupTitle"] = "Alineación",
        ["ui.kn.onPitch"] = "En el campo",
        ["ui.kn.zones"] = "Zonas",
        ["ui.kn.mobRow"] = "TURBA (si hay empate)",
        ["ui.kn.coverage"] = "Cobertura",
        ["ui.kn.zonesTip"] = "Pinta los tercios y las bandas que nombran los perks de inicio. Tecla Z o botón Y.",
        ["ui.kn.coverageTip"] = "Cuántos jugadores cubren cada casilla y dónde quedan huecos. Tecla C o botón X.",
        ["ui.kn.inputMouse"] = "RATÓN  clic en un jugador: su ficha · pasa el ratón por un icono: qué significa · Q / E: pestañas",
        ["ui.kn.inputPad"] = "MANDO  cruceta: elegir jugador · gatillos: pestañas · la ficha y el cofre se manejan con ratón por ahora",

        ["ui.kn.tip.strength"] = "Gana choques y entradas, empuja y aguanta empujones. Con más fuerza, sus entradas hacen más daño.",
        ["ui.kn.tip.speed"] = "Llega antes al balón, corre más con él y persigue mejor. Al portero le ayuda en las paradas cercanas.",
        ["ui.kn.tip.technique"] = "Pases, tiros, regates y controles. Con poca técnica, el balón le rebota en la espinilla.",
        ["ui.kn.tip.stamina"] = "Tarda más en cansarse, se recupera antes y aguanta mejor una entrada sin romperse.",
        ["ui.kn.tip.leash"] = "Hasta dónde se aleja de su casilla. Mucha correa: aparece por todas partes y deja huecos atrás.",
        ["ui.kn.tip.modifier"] = "Base {0}, objeto {1}: juega con {2}.",
        ["ui.kn.tip.pos.Goalkeeper"] = "Para lo que puede. Siempre empieza en su casilla, bajo los palos.",
        ["ui.kn.tip.pos.Defender"] = "Corta, marca y despeja. Juega cerca de su portería.",
        ["ui.kn.tip.pos.Midfielder"] = "Recupera, reparte y sube cuando puede. El que más corre.",
        ["ui.kn.tip.pos.Forward"] = "Remata. Lo demás le importa bastante poco.",
        ["ui.kn.tip.starter"] = "Sale de inicio. Cámbialo en la pestaña de Alineación.",
        ["ui.kn.tip.bench"] = "Espera en el banquillo y entra si cae un titular.",
        ["ui.kn.tip.level"] = "Sube con los partidos jugados. Media de atributos: {0}. Rareza: {1}, {2} huecos de perk.",
        ["ui.kn.tip.slots"] = "Huecos de perk ocupados y libres, y si lleva objeto.",
        ["ui.kn.tip.state.Healthy"] = "Listo para jugar.",
        ["ui.kn.tip.state.MinorInjury"] = "Juega tocado: −15 % a todo en el próximo partido. Se puede acumular.",
        ["ui.kn.tip.state.SevereInjury"] = "No puede alinearse hasta que lo cure la clínica.",
        ["ui.kn.tip.state.Dead"] = "Ya no juega. Lo que llevaba ha vuelto al cofre.",
        ["ui.kn.tip.trait.Aggressive"] = "Entra y bloquea mucho más, y sus entradas son más duras.",
        ["ui.kn.tip.trait.Fast"] = "Un poco más rápido, y persigue y regatea más a menudo.",
        ["ui.kn.tip.trait.Scorer"] = "Tira más y tira mejor. Se ofrece para rematar.",
        ["ui.kn.tip.trait.LongShot"] = "Se atreve a tirar desde dos casillas más lejos.",
        ["ui.kn.tip.trait.Cerebral"] = "Pasa más y mejor, sobre todo en largo. Regatea menos.",
        ["ui.kn.tip.trait.Dirty"] = "Hace más faltas y lesiona más, pero gana más balones.",
        ["ui.kn.tip.trait.Resilient"] = "Se cansa mucho menos y se lesiona menos.",
        ["ui.kn.tip.trait.Coward"] = "Evita las entradas, los choques y los regates. Muy sensato. Muy inútil.",
        ["ui.kn.tip.trait.Leader"] = "Los compañeros que tiene al lado juegan un poco mejor.",
        ["ui.kn.tip.trait.Lazy"] = "Repliega, marca y se ofrece menos de lo que debería.",
        ["ui.kn.tip.trait.Cat"] = "Portero: para mejor los tiros de cerca.",
        ["ui.kn.tip.trait.Wall"] = "Portero: para mejor los tiros de lejos.",
        ["ui.kn.tip.trait.Rusher"] = "Portero: sale mucho a por el balón y se aleja más de la portería.",
        ["ui.kn.tip.racial"] = "Habilidad racial: la tiene toda la plantilla y no ocupa hueco.",
        ["ui.kn.tip.emptySlot"] = "Hueco de perk libre. Se llena en el mercado o con las recompensas.",
        ["ui.kn.tip.noItem"] = "No lleva objeto. Equípale uno del cofre o cómpralo en el mercado.",
        ["ui.kn.tip.relic"] = "Reliquia: la dejó un jugador muerto, según lo que hizo en vida. No se compra.",
        ["ui.kn.tip.itemRarity"] = "Objeto {0}.",
        ["ui.kn.tip.chest"] = "Objetos que nadie lleva puestos: botín de liga, reliquias y lo que dejan los muertos. Equiparlos es gratis.",
        ["ui.kn.tip.consumables"] = "Dos huecos. Lo que llevas va al partido: lo activas tú con un clic, o salta solo si le pones un disparador.",
        ["ui.kn.tip.equip"] = "Pone el objeto elegido del cofre a este jugador. Si ya llevaba uno, el suyo vuelve al cofre.",
        ["ui.kn.tip.store"] = "Le quita el objeto y lo guarda en el cofre.",
        ["ui.kn.tip.pass"] = "Le da su objeto a otro jugador. Si ese ya llevaba uno, el suyo vuelve al cofre.",
        ["ui.kn.tip.manual"] = "Manual: lo activas tú durante el partido, con el botón del tablero.",
        ["ui.kn.tip.conditional"] = "Condicional: salta solo cuando {0}.",
        ["ui.kn.tip.makeManual"] = "Lo activarás tú con un clic en el tablero del partido.",
        ["ui.kn.tip.cycleTrigger"] = "Que salte solo cuando pase lo que le digas. Púlsalo otra vez para cambiar cuándo.",
        ["ui.kn.makeManual"] = "Hacer manual",
        ["ui.kn.trigger"] = "Salta si…",
        ["ui.kn.pickConsumable"] = "Elige un consumible para ver qué hace",
        ["ui.kn.manual"] = "Manual",
        ["ui.kn.conditional"] = "Si {0}",
        ["ui.kn.copies"] = "×{0}",
        ["ui.kn.tip.nickname"] = "Se lo ha ganado en esta run: {0} o más de {1}. Es fama, no ventaja: no cambia cómo juega.",
        ["ui.kn.run"] = "LA RUN",
        ["ui.kn.runMatches"] = "partidos",
        ["ui.kn.runGoals"] = "goles",
        ["ui.kn.runAssists"] = "asistencias",
        ["ui.kn.runTacklesWon"] = "entradas ganadas",
        ["ui.kn.runFouls"] = "faltas",
        ["ui.kn.runCards"] = "tarjetas",
        ["ui.kn.runInjuriesCaused"] = "lesiones causadas",
        ["ui.kn.runDeath"] = "+1 muerte",
        ["ui.kn.runDeaths"] = "+{0} muertes",
        ["ui.kn.runInjuriesSuffered"] = "lesiones sufridas",
        ["ui.nick.stat.Matches"] = "partidos jugados",
        ["ui.nick.stat.Goals"] = "goles",
        ["ui.nick.stat.Assists"] = "asistencias",
        ["ui.nick.stat.Tackles"] = "entradas",
        ["ui.nick.stat.TacklesWon"] = "entradas ganadas",
        ["ui.nick.stat.Fouls"] = "faltas",
        ["ui.nick.stat.Cards"] = "tarjetas",
        ["ui.nick.stat.InjuriesCaused"] = "lesiones causadas",
        ["ui.nick.stat.DeathsCaused"] = "muertes causadas",
        ["ui.nick.stat.InjuriesSuffered"] = "lesiones sufridas",
    };

    /// <summary>Texto de la clave; si falta, la propia clave (un texto que falta debe verse, no ocultarse).</summary>
    public static string Get(string key) => Es.TryGetValue(key, out string? value) ? value : key;

    /// <summary>
    /// Nombre de un elemento del catálogo (objeto, perk, consumible) en el idioma del juego
    /// (<see cref="Underleague.Game.Data.GameData.Language"/>). Las pantallas no leen <c>Name.Es</c> a mano.
    /// </summary>
    public static string Name(Underleague.Sim.Data.LocalizedName name) =>
        string.Equals(Underleague.Game.Data.GameData.Language, "en", System.StringComparison.Ordinal) ? name.En : name.Es;

    /// <summary>Texto de la clave con los argumentos sustituidos en <c>{0}</c>, <c>{1}</c>...</summary>
    public static string Get(string key, params object[] args) =>
        string.Format(System.Globalization.CultureInfo.InvariantCulture, Get(key), args);

    /// <summary>
    /// Frase con la cifra en singular o plural: la clave singular si <paramref name="value"/> es 1 (sin
    /// marcador: lleva el «1» escrito) y la plural con la cifra en <c>{0}</c> en cualquier otro caso. Ninguna
    /// pantalla dice «1 bajas» ni deja un «baja(s)» (ADR 0163).
    /// </summary>
    public static string Plural(int value, string singularKey, string pluralKey) =>
        value == 1 ? Get(singularKey) : Get(pluralKey, value);

    /// <summary>
    /// El subtítulo de un nodo con, si acaba de entrar devolviéndose una apuesta tomada para otro nodo
    /// (ADR 0157), «el corredor te devuelve N de oro»: la devolución no puede pasar sin explicación.
    /// </summary>
    public static string WithBetRefund(string subtitle, Underleague.Sim.Run.RunState state)
    {
        int refunded = state.Counter(Underleague.Sim.Run.RunState.BetRefundedCounter);
        return refunded > 0 ? subtitle + " · " + Get("ui.bet.refunded", refunded) : subtitle;
    }

    /// <summary>
    /// Cifra con signo explícito ("+15" / "−8"), para el criterio del árbitro y sus desplazamientos
    /// (RF-062, RF-063): en el ojeo, en el tablero del partido y en el texto flotante que acompaña cada
    /// movimiento. El menos es el guion U+2212, no un guion normal (mismo signo que ya usa el resto de la
    /// interfaz, p. ej. <c>ui.pregon.tray.playOnSub</c>).
    /// </summary>
    public static string Signed(int value) => value >= 0
        ? "+" + value.ToString(System.Globalization.CultureInfo.InvariantCulture)
        : "−" + (-value).ToString(System.Globalization.CultureInfo.InvariantCulture);
}
