using System.Collections.Generic;

namespace Underleague.Game.Ui;

/// <summary>
/// Textos de la interfaz por clave (RT-073). Todo lo que el jugador lee sale de aquí o de
/// <c>data/l10n/&lt;idioma&gt;/templates.json</c> a través de <c>Sim.Data.Localization</c>; en la pantalla
/// no hay ni una cadena escrita a mano.
/// <para>
/// El vocabulario del juego —posiciones, atributos, rasgos, etiquetas, relaciones de vínculo— ya vive en
/// <c>data/l10n</c> y se lee del catálogo. Lo que hay en esta tabla es solo el <b>mobiliario de la
/// pantalla</b> (títulos, ayudas de control, etiquetas de campo), que todavía no tiene fichero de datos.
/// La tabla está indexada por clave precisamente para que en fase 4 el cuerpo de <see cref="Get(string)"/>
/// pase a leer <c>data/l10n/&lt;idioma&gt;/ui.json</c> sin tocar ninguna pantalla.
/// </para>
/// </summary>
public static class UiText
{
    private static readonly Dictionary<string, string> Es = new()
    {
        ["ui.team.title"] = "EQUIPO",
        ["ui.team.subtitle"] = "{0} · {1} · plantilla de {2}",
        ["ui.team.roster"] = "PLANTILLA",
        ["ui.team.placeholderClub"] = "club de pruebas",
        ["ui.team.starters"] = "TITULARES",
        ["ui.team.bench"] = "SUPLENTES",
        ["ui.team.pitch"] = "COLOCACIÓN",
        ["ui.team.pitchHint"] = "mitad propia, 8 columnas · el portero no se mueve de su casilla",
        ["ui.team.coverage"] = "COBERTURA DEL EQUIPO",
        ["ui.team.coverageLegend"] = "cubren",
        ["ui.team.coverageButton"] = "Cobertura del equipo (X / C)",
        ["ui.team.coverageHint"] = "jugadores que cubren cada casilla · {0} casillas sin cubrir",
        ["ui.team.coverageHole"] = "hueco",
        ["ui.team.legendZone"] = "zona: aquí estará",
        ["ui.team.legendMargin"] = "margen: hasta aquí llega",
        ["ui.team.legendLink"] = "vínculo",
        ["ui.team.legendCreated"] = "se crea",
        ["ui.team.legendBroken"] = "se rompe",
        ["ui.team.links"] = "VÍNCULOS",
        ["ui.team.lineup"] = "ALINEACIÓN",
        ["ui.team.lineupRow"] = "{0} · {1} · columna {2}, fila {3} · {4} {5}",
        ["ui.team.linkOne"] = "vínculo",
        ["ui.team.linkMany"] = "vínculos",
        ["ui.team.moreChanges"] = "y {0} cambios más en el resto de la alineación",
        ["ui.link.Beside"] = "al lado",
        ["ui.link.Ahead"] = "delante",
        ["ui.link.Behind"] = "detrás",
        ["ui.link.Left"] = "izquierda",
        ["ui.link.Right"] = "derecha",
        ["ui.link.DiagonalAhead"] = "diagonal delante",
        ["ui.link.DiagonalBehind"] = "diagonal detrás",
        ["ui.team.linksNone"] = "sin vínculos: nadie en las casillas contiguas",
        ["ui.team.linkOf"] = "{0}: {1}",
        ["ui.team.created"] = "+ {1} ({0})",
        ["ui.team.broken"] = "- {1} ({0})",
        ["ui.team.moving"] = "MOVIENDO A {0}",
        ["ui.team.dropHint"] = "suelta en una casilla de la mitad propia",
        ["ui.team.selected"] = "SELECCIONADO",
        ["ui.team.nobody"] = "selecciona a un jugador para ver su zona de acción",
        ["ui.card.level"] = "nivel {0}",
        ["ui.card.rarity.Common"] = "común",
        ["ui.card.rarity.Rare"] = "raro",
        ["ui.card.rarity.Legendary"] = "legendario",
        ["ui.card.traits"] = "RASGOS",
        ["ui.card.perks"] = "PERKS",
        ["ui.card.ability"] = "HABILIDAD RACIAL",
        ["ui.card.perkSlot"] = "slot libre",
        ["ui.card.item"] = "OBJETO",
        ["ui.card.itemNone"] = "sin objeto (equipamiento: fase 2)",
        ["ui.card.state"] = "ESTADO",
        ["ui.card.salary"] = "SALARIO",
        ["ui.card.salaryNone"] = "sin salario (economía: fase 2)",
        ["ui.card.links"] = "VÍNCULOS",
        ["ui.card.style"] = "estilo",
        ["ui.card.bench"] = "suplente",
        ["ui.state.Healthy"] = "sano",
        ["ui.state.MinorInjury"] = "lesión leve",
        ["ui.state.SevereInjury"] = "lesión grave",
        ["ui.state.Dead"] = "muerto",
        ["ui.pos.Goalkeeper"] = "POR",
        ["ui.pos.Defender"] = "DEF",
        ["ui.pos.Midfielder"] = "CEN",
        ["ui.pos.Forward"] = "DEL",
        ["ui.input.mouse"] = "RATÓN  clic: seleccionar · arrastrar y soltar: colocar · clic en la ficha: expandir",
        ["ui.input.pad"] = "MANDO  cruceta: mover cursor · A: seleccionar y coger/soltar · B: cancelar · X: cobertura",

        // --- esqueleto jugable (docs/ui-run-minima.md) ---
        ["ui.nav.back"] = "Volver",
        ["ui.nav.map"] = "Volver al mapa",
        ["ui.nav.team"] = "Equipo",
        ["ui.nav.continue"] = "Continuar",
        ["ui.nav.pendingTitle"] = "PANTALLA PENDIENTE",
        ["ui.nav.pendingBody"] = "{0} todavía no existe: la escribe el otro paquete de la interfaz mínima. La run no se bloquea por eso.",
        ["ui.nav.pendingMatch"] = "Se juega el partido aquí de forma provisional: se resuelve y se enseña el resultado, sin log y sin informe.",

        ["ui.start.title"] = "UNDERLEAGUE",
        ["ui.start.subtitle"] = "carnicería administrada · esqueleto jugable de la fase 2",
        ["ui.start.club"] = "CLUB",
        ["ui.start.clubHint"] = "todos los jugadores del club inicial son de una misma raza (RF-004)",
        ["ui.start.seed"] = "SEMILLA",
        ["ui.start.seedHint"] = "la misma semilla juega la misma run: mismos mapas, mismos rivales, mismos dados",
        ["ui.start.random"] = "Aleatoria",
        ["ui.start.begin"] = "Empezar run",
        ["ui.start.continue"] = "Continuar la run guardada",
        ["ui.start.noSave"] = "no hay ninguna run guardada",
        ["ui.start.saved"] = "hay una run guardada: acto {0}, {1} de oro, {2} disponibles",
        ["ui.start.ability"] = "habilidad racial",
        ["ui.start.chosen"] = "elegido: {0}",
        ["ui.start.badSeed"] = "la semilla debe ser un número entero; se usa {0}",

        ["ui.map.title"] = "MAPA",
        ["ui.map.subtitle"] = "acto {0} de {1} · {2} · {3} de oro",
        ["ui.map.available"] = "DISPONIBLES {0} / mínimo {1}",
        ["ui.map.availableHint"] = "por debajo del mínimo la run termina (RF-002b)",
        ["ui.map.choose"] = "ADÓNDE IR",
        ["ui.map.graph"] = "ACTO {0}",
        ["ui.map.progress"] = "nodo {0} de la run · {1} nodos por acto",
        ["ui.map.marketHere"] = "mercado: la única tienda del juego",
        ["ui.map.marketHops"] = "mercado a {0} saltos desde aquí",
        ["ui.map.marketNone"] = "sin mercado alcanzable por este camino",
        ["ui.map.difficulty"] = "dificultad {0}/5 · {1}",
        ["ui.map.boss"] = "jefe del acto {0}",
        ["ui.map.bossHidden"] = "su modificador de regla no se conoce hasta llegar",
        ["ui.map.legend"] = "borde dorado: adónde puedes ir · anillo doble: mercado · relleno: por donde has pasado · apagado: fuera de alcance desde tu carril",
        ["ui.map.state"] = "ESTADO DE LA RUN",
        ["ui.map.roster"] = "plantilla {0} de {1} · {2} caídos",
        ["ui.map.quit"] = "Guardar y salir",
        ["ui.map.abandon"] = "Abandonar la run",
        ["ui.map.abandonSure"] = "¿Seguro? Se pierde",
        ["ui.map.noNodes"] = "no hay nodos accesibles",

        ["ui.scout.title"] = "OJEO",
        ["ui.scout.subtitle"] = "{0} · dificultad {1}/5 · {2}",
        ["ui.scout.rival"] = "PLANTILLA RIVAL",
        ["ui.scout.build"] = "BUILD",
        ["ui.scout.buildLine"] = "{0} · nivel medio {1} · {2}",
        ["ui.scout.referee"] = "ÁRBITRO",
        ["ui.scout.refereeLine"] = "{0} · criterio {1}",
        ["ui.scout.refereeGap"] = "los rasgos de árbitro y los sobornos son de fase 3: hoy todos son neutros (RF-061)",
        ["ui.scout.lethal"] = "PERKS LETALES",
        ["ui.scout.lethalNone"] = "ninguno: este rival no puede matar a nadie",
        ["ui.scout.lethalLine"] = "{0} lleva {1}: {2}",
        ["ui.scout.risk"] = "RIESGO DE MUERTE DE TUS TITULARES",
        ["ui.scout.riskLine"] = "{0}: {1}",
        ["ui.scout.riskNone"] = "sin riesgo de muerte con esta alineación",
        ["ui.scout.warnings"] = "ANTES DE CONFIRMAR",
        ["ui.scout.warnShorthanded"] = "juegas en inferioridad: con 5 en campo, una sola baja termina la run (RF-002d)",
        ["ui.scout.warnSevere"] = "{0} sale con una lesión grave sin tratar: si vuelve a lesionarse, muere (RF-093)",
        ["ui.scout.warnLethal"] = "{0} puede morir en este partido: {1}",
        ["ui.scout.lineup"] = "Alinear",
        ["ui.scout.start"] = "Empezar partido",
        ["ui.scout.boss"] = "MODIFICADORES DEL JEFE",
        ["ui.scout.bossHidden"] = "el modificador se descubre al llegar aquí, y ya lo has hecho",
        ["ui.scout.starters"] = "TU ONCE",

        ["ui.node.clinicTitle"] = "CLÍNICA",
        ["ui.node.clinicBody"] = "coste {0} de oro por jugador · resultado garantizado: vuelve a sano, sin efectos secundarios (RF-094)",
        ["ui.node.clinicNone"] = "no hay ningún jugador con lesión grave que tratar",
        ["ui.node.clinicPoor"] = "no te llega el oro: tienes {0} y cuesta {1}",
        ["ui.node.treat"] = "Tratar a {0} ({1} de oro)",
        ["ui.node.treated"] = "{0} vuelve a estar sano",
        ["ui.node.enrollTitle"] = "INSCRIPCIÓN",
        ["ui.node.enrollBody"] = "coste {0} de oro · amplía la plantilla en un hueco, hasta {1} (RF-020)",
        ["ui.node.enrollState"] = "plantilla {0} de {1} · quedan {2} huecos por comprar",
        ["ui.node.enrollFull"] = "la plantilla ya está en su techo: no queda hueco que comprar",
        ["ui.node.enrollBuy"] = "Comprar el hueco ({0} de oro)",
        ["ui.node.enrolled"] = "plantilla ampliada a {0}",
        ["ui.node.trainTitle"] = "ENTRENAMIENTO",
        ["ui.node.trainBody"] = "sin coste · {0} de experiencia a cada jugador disponible (los canteranos, un {1}% más)",
        ["ui.node.train"] = "Entrenar",
        ["ui.node.trained"] = "entrenados {0} jugadores; {1} suben de nivel",
        ["ui.node.eventTitle"] = "EVENTO",
        ["ui.node.eventBody"] = "sin coste · un pago entre {0} y {1} de oro (RF-114j)",
        ["ui.node.eventGo"] = "Ver qué pasa",
        ["ui.node.evented"] = "el evento deja {0} de oro",
        ["ui.node.gold"] = "oro: {0}",
        ["ui.node.leave"] = "Salir al mapa",
        ["ui.node.error"] = "no se pudo: {0}",

        ["ui.end.victory"] = "VICTORIA",
        ["ui.end.defeat"] = "DERROTA",
        ["ui.end.victoryBody"] = "el jefe del acto 3 ha caído. La run termina en victoria (RF-002).",
        ["ui.end.causeBoss"] = "causa: se perdió un partido de jefe (RF-002b)",
        ["ui.end.causePlayers"] = "causa: los jugadores disponibles bajaron de {0} (RF-002b)",
        ["ui.end.stats"] = "actos superados {0} de {1} · nodos {2} · partidos {3} ganados de {4} · oro {5}",
        ["ui.end.roster"] = "PLANTILLA FINAL",
        ["ui.end.fallen"] = "CAÍDOS",
        ["ui.end.fallenNone"] = "ninguno: la run termina con la plantilla entera viva",
        ["ui.end.fallenLine"] = "{0} · {1} · nivel {2}",
        ["ui.end.again"] = "Otra run",
        ["ui.end.seed"] = "semilla {0} · {1}",

        ["ui.kind.LeagueMatch"] = "partido de liga",
        ["ui.kind.EliteMatch"] = "partido de élite",
        ["ui.kind.Market"] = "mercado",
        ["ui.kind.Clinic"] = "clínica",
        ["ui.kind.Workshop"] = "taller",
        ["ui.kind.Training"] = "entrenamiento",
        ["ui.kind.Event"] = "evento",
        ["ui.kind.Boss"] = "jefe",
        ["ui.kind.Enrollment"] = "inscripción",
        ["ui.kind.short.LeagueMatch"] = "LIG",
        ["ui.kind.short.EliteMatch"] = "ELI",
        ["ui.kind.short.Market"] = "MER",
        ["ui.kind.short.Clinic"] = "CLI",
        ["ui.kind.short.Workshop"] = "TAL",
        ["ui.kind.short.Training"] = "ENT",
        ["ui.kind.short.Event"] = "EVE",
        ["ui.kind.short.Boss"] = "JEF",
        ["ui.kind.short.Enrollment"] = "INS",
        ["ui.difficulty.1"] = "asequible",
        ["ui.difficulty.2"] = "seria",
        ["ui.difficulty.3"] = "dura",
        ["ui.difficulty.4"] = "muy dura",
        ["ui.difficulty.5"] = "letal",
        ["ui.risk.percent"] = "{0},{1}%",
        ["ui.input.mouseOnly"] = "RATÓN  clic: elegir · clic en una ficha: expandirla",
        ["ui.input.padPending"] = "MANDO  pendiente en esta pantalla: la navegación con mando está hecha en Equipo (UI-006)",

        // --- partido, informe, recompensa y mercado (docs/ui-run-minima.md) ---
        ["ui.card.rarity.Uncommon"] = "poco común",

        ["ui.match.title"] = "PARTIDO",
        ["ui.match.subtitle"] = "{0} · dificultad {1}/5 · acto {2} · árbitro {3}",
        ["ui.match.log"] = "LOG DEL PARTIDO",
        ["ui.match.highlights"] = "SUCESOS CLAVE",
        ["ui.match.hint"] = "el partido ya está resuelto: esto es lo que pasó. Pausa, retrocede y vuelve a ver la jugada que quieras.",
        ["ui.match.minute"] = "minuto {0}",
        ["ui.match.kickoff"] = "antes del saque",
        ["ui.match.golden"] = "prórroga de turba: el siguiente gol gana (RF-055b)",
        ["ui.match.forfeit"] = "incomparecencia: un equipo se quedó sin jugadores (RF-059)",
        ["ui.match.final"] = "FINAL · {0}",
        ["ui.match.won"] = "victoria",
        ["ui.match.lost"] = "derrota",
        ["ui.match.progress"] = "{0} de {1} sucesos",
        ["ui.match.pause"] = "Pausa",
        ["ui.match.resume"] = "Seguir",
        ["ui.match.speed"] = "Velocidad x{0}",
        ["ui.match.all"] = "Mostrar todo",
        ["ui.match.report"] = "Ir al informe",
        ["ui.match.cancelled"] = "anulado por un perk",
        ["ui.match.none"] = "no hay ningún partido que enseñar",
        ["ui.match.highlightsNone"] = "todavía no ha pasado nada digno de mención",

        // --- campo del partido (traza de posiciones, MatchTrace) ---
        ["ui.match.pitch"] = "CAMPO",
        ["ui.match.clock"] = "minuto {0} · tick {1} de {2} · {3}",
        ["ui.match.stepBack"] = "◀ tick",
        ["ui.match.stepForward"] = "tick ▶",
        ["ui.match.end"] = "Al final",
        ["ui.match.zoneOn"] = "Correa: sí",
        ["ui.match.zoneOff"] = "Correa: no",
        ["ui.match.selected"] = "{0} · {1} · dorsal {2} · {3}",
        ["ui.match.selectHint"] = "clic en una ficha para seguirla y ver su correa",
        ["ui.match.legendOwn"] = "tu equipo",
        ["ui.match.legendRival"] = "rival",
        ["ui.match.legendBall"] = "balón",
        ["ui.match.legendCarrier"] = "lo lleva",
        ["ui.match.legendZone"] = "correa del elegido",
        ["ui.match.legendMark"] = "marca a (asignado)",
        ["ui.match.legendMarking"] = "yendo a por él",
        ["ui.match.markOn"] = "Marcaje: sí",
        ["ui.match.markOff"] = "Marcaje: no",
        ["ui.match.doing"] = "quiere {0}",
        ["ui.match.marking"] = "marca a {0} (dorsal {1})",
        ["ui.match.markAssigned"] = "marca al {0}",
        ["ui.match.noAction"] = "todavía no ha decidido nada",
        ["ui.match.noTrace"] = "este partido se reprodujo sin traza: no hay campo que enseñar",

        ["ui.phase.Kickoff"] = "saque",
        ["ui.phase.OpenPlay"] = "juego",
        ["ui.phase.Restart"] = "reanudación",
        ["ui.phase.Penalty"] = "penalti",
        ["ui.phase.RegulationEnd"] = "fin del reglamentario",
        ["ui.phase.MobGoldenGoal"] = "turba: gol de oro",
        ["ui.phase.Finished"] = "final",

        ["ui.pstate.Positioning"] = "coloca",
        ["ui.pstate.Chasing"] = "persigue",
        ["ui.pstate.Dribbling"] = "regatea",
        ["ui.pstate.Passing"] = "pasa",
        ["ui.pstate.Shooting"] = "tira",
        ["ui.pstate.Tackling"] = "entra",
        ["ui.pstate.Blocking"] = "carga",
        ["ui.pstate.KnockedDown"] = "derribado",
        ["ui.pstate.Injured"] = "lesionado",
        ["ui.pstate.Celebrating"] = "celebra",
        ["ui.pstate.SentOff"] = "expulsado",

        // Las trece acciones de la tabla de utilidad (RT-098). Se leen detrás de "quiere ...", así que van
        // en infinitivo: es lo que el jugador está intentando hacer, no lo que ha conseguido.
        ["ui.paction.ChaseBall"] = "ir a por el balón",
        ["ui.paction.MarkOpponent"] = "marcar a un rival",
        ["ui.paction.OfferSupport"] = "ofrecerse para el pase",
        ["ui.paction.CoverSpace"] = "cubrir su espacio",
        ["ui.paction.Dribble"] = "regatear",
        ["ui.paction.Shoot"] = "tirar",
        ["ui.paction.Tackle"] = "entrar a por el balón",
        ["ui.paction.Retreat"] = "replegarse",
        ["ui.paction.FindSpace"] = "buscar un hueco",
        ["ui.paction.PressCarrier"] = "presionar al que lleva el balón",
        ["ui.paction.ShortPass"] = "dar un pase corto",
        ["ui.paction.LongPass"] = "abrir el juego en largo",
        ["ui.paction.Block"] = "cargar contra un rival",

        ["ui.ev.MatchStart"] = "empieza el partido",
        ["ui.ev.MatchEnd"] = "final del partido",
        ["ui.ev.MobStart"] = "la turba invade el campo",
        ["ui.ev.RefereeLeaves"] = "el árbitro abandona el campo",
        ["ui.ev.PassCompleted"] = "{0} encuentra a {1}",
        ["ui.ev.PassFailed"] = "{0} pierde el pase",
        ["ui.ev.DribbleWon"] = "{0} regatea a {1}",
        ["ui.ev.DribbleLost"] = "{0} pierde el balón ante {1}",
        ["ui.ev.AerialDuel"] = "{0} salta contra {1}",
        ["ui.ev.Tackle"] = "{0} entra a {1}",
        ["ui.ev.Recovery"] = "{0} recupera el balón",
        ["ui.ev.Shot"] = "{0} dispara",
        ["ui.ev.Goal"] = "GOL de {0}",
        ["ui.ev.Save"] = "{0} para el tiro de {1}",
        ["ui.ev.Foul"] = "{0} hace falta a {1}",
        ["ui.ev.Card"] = "{0} ve tarjeta",
        ["ui.ev.Injury"] = "{0} cae lesionado",
        ["ui.ev.Death"] = "{0} MUERE en el campo",
        ["ui.ev.Substitution"] = "{0} entra por {1}",
        ["ui.ev.ConsumableUsed"] = "{0} usa un consumible",
        ["ui.ev.PassAttempted"] = "{0} intenta el pase a {1}",
        ["ui.ev.DribbleAttempted"] = "{0} encara a {1}",
        ["ui.ev.PlayStart"] = "arranca la jugada",
        ["ui.ev.PlayEnd"] = "se acaba la jugada",

        ["ui.report.title"] = "INFORME",
        ["ui.report.subtitle"] = "{0} {1}-{2} {3} · {4} · {5} minutos",
        ["ui.report.victory"] = "VICTORIA",
        ["ui.report.defeat"] = "DERROTA",
        ["ui.report.perks"] = "PERKS ACTIVADOS",
        ["ui.report.perksNone"] = "ningún perk tuyo llegó a activarse en este partido",
        ["ui.report.perkRow"] = "{0} · lo lleva {1}",
        ["ui.report.activations"] = "{0} activaciones",
        ["ui.report.activationOne"] = "1 activación",
        ["ui.report.contribution"] = "en sus activaciones: {0}",
        ["ui.report.contribNone"] = "en sus activaciones no cayó ningún gol, lesión ni recuperación",
        ["ui.report.cGoals"] = "{0} goles",
        ["ui.report.cGoal"] = "1 gol",
        ["ui.report.cInjuries"] = "{0} lesiones causadas",
        ["ui.report.cInjury"] = "1 lesión causada",
        ["ui.report.cRecoveries"] = "{0} recuperaciones",
        ["ui.report.cRecovery"] = "1 recuperación",
        ["ui.report.cSaves"] = "{0} paradas",
        ["ui.report.cSave"] = "1 parada",
        ["ui.report.cCancels"] = "{0} sucesos anulados",
        ["ui.report.cCancel"] = "1 suceso anulado",
        ["ui.report.items"] = "EQUIPAMIENTO",
        ["ui.report.itemsNone"] = "nadie salió al campo con objeto",
        ["ui.report.itemRow"] = "{0} · lo lleva {1}",
        ["ui.report.itemRestricted"] = "no le aporta nada: no es de su raza",
        ["ui.report.casualties"] = "BAJAS",
        ["ui.report.casualtiesNone"] = "sin bajas: la plantilla sale entera",
        ["ui.report.deathRow"] = "MUERE {0} · minuto {1}",
        ["ui.report.injuryRow"] = "{0} · {1} · minuto {2}",
        ["ui.report.cause"] = "por {0}",
        ["ui.report.cards"] = "TARJETAS",
        ["ui.report.cardsNone"] = "el árbitro no sacó ninguna",
        ["ui.report.cardRow"] = "{0} · {1} · minuto {2}",
        ["ui.report.cardYellow"] = "amarilla",
        ["ui.report.cardRed"] = "roja",
        ["ui.report.sideOwn"] = "tuya",
        ["ui.report.sideRival"] = "del rival",
        ["ui.report.gold"] = "ORO GANADO",
        ["ui.report.goldNone"] = "perder no paga (RF-114g)",
        ["ui.report.goldBase"] = "base del acto {0}",
        ["ui.report.goldDifficulty"] = "dificultad {0}/5 (x{1}%)",
        ["ui.report.goldNode"] = "{0} (+{1}%)",
        ["ui.report.goldObjective"] = "partido excelente cumplido: {0}",
        ["ui.report.goldObjectiveFailed"] = "partido excelente no cumplido: {0}",
        ["ui.report.goldTotal"] = "TOTAL",
        ["ui.report.goldNow"] = "oro de la run: {0}",
        ["ui.report.referee"] = "ÁRBITRO",
        ["ui.report.refereeBias"] = "criterio {0} al empezar, {1} al terminar",
        ["ui.report.refereeFouls"] = "faltas: {0} tuyas, {1} del rival",
        ["ui.report.refereeCards"] = "tarjetas: {0} tuyas, {1} del rival",
        ["ui.report.refereeGap"] = "las faltas no señaladas todavía no se registran: hueco conocido de RF-119",
        ["ui.report.continue"] = "Continuar",
        ["ui.report.none"] = "todavía no se ha jugado ningún partido",
        ["ui.report.deaths"] = "{0} MUERTOS",
        ["ui.report.death"] = "1 MUERTO",

        ["ui.objective.WinByThreeOrMore"] = "ganar por 3 goles o más",
        ["ui.objective.CleanSheet"] = "ganar sin encajar",
        ["ui.objective.WinShortHanded"] = "ganar en inferioridad",
        ["ui.objective.WinWithYouthScorer"] = "ganar con gol de un canterano",

        ["ui.reward.title"] = "RECOMPENSA",
        ["ui.reward.subtitle"] = "{0} · elección {1} de {2} · {3} de oro",
        ["ui.reward.badgePerk"] = "PERK",
        ["ui.reward.badgePlayer"] = "JUGADOR",
        ["ui.reward.badgeItem"] = "OBJETO",
        ["ui.reward.choose"] = "Elegir",
        ["ui.reward.assign"] = "Elegir y asignar",
        ["ui.reward.noCarrierNeeded"] = "entra en la plantilla: no hay a quién asignárselo",
        ["ui.reward.confirm"] = "Dárselo a {0}",
        ["ui.reward.decline"] = "Rechazar la recompensa",
        ["ui.reward.declineHint"] = "con los perks irreversibles y los slots contados, quedarse con la menos mala puede ser peor que no quedarse con nada (ADR 0043)",
        ["ui.reward.reroll"] = "Repetir la tirada ({0} de oro)",
        ["ui.reward.rerollUsed"] = "el reroll de este nodo ya se ha usado: uno por nodo (RF-071b)",
        ["ui.reward.rerollPoor"] = "repetir cuesta {0} de oro y tienes {1}",
        ["ui.reward.carrier"] = "A QUIÉN SE LO DAS",
        ["ui.reward.carrierPerk"] = "un perk asignado NO SE PUEDE RETIRAR ni transferir (RF-072): la decisión dura toda la run.",
        ["ui.reward.carrierItem"] = "cada jugador lleva un objeto y solo uno: el que tuviera vuelve al almacén.",
        ["ui.reward.carrierRow"] = "{0} · {1} · nivel {2} · {3} · {4}",
        ["ui.reward.slots"] = "{0} slots libres",
        ["ui.reward.slot"] = "1 slot libre",
        ["ui.reward.carrierHasItem"] = "lleva {0}",
        ["ui.reward.carrierNoItem"] = "sin objeto",
        ["ui.reward.blockRoster"] = "plantilla llena ({0} de {1}): hay que rechazar o hacer sitio (RF-020)",
        ["ui.reward.blockCarrier"] = "nadie de tu plantilla puede llevarlo",
        ["ui.reward.none"] = "no hay ninguna recompensa que elegir",
        ["ui.reward.pick"] = "elige un artículo para ver a quién puedes dárselo",
        ["ui.reward.optionsLeague"] = "un partido de liga ofrece una elección entre dos (ADR 0049)",
        ["ui.reward.optionsElite"] = "un partido de élite ofrece una entre tres, con mejor rareza",
        ["ui.reward.optionsBoss"] = "el jefe ofrece dos elecciones entre tres, y cura la plantilla",
        ["ui.reward.error"] = "no se pudo: {0}",

        ["ui.market.title"] = "MERCADO",
        ["ui.market.subtitle"] = "acto {0} · {1} de oro · plantilla {2} de {3} · la única tienda del juego, y no se renueva",
        ["ui.market.players"] = "JUGADORES",
        ["ui.market.perks"] = "PERKS",
        ["ui.market.items"] = "EQUIPAMIENTO",
        ["ui.market.consumables"] = "CONSUMIBLES",
        ["ui.market.sell"] = "VENDER JUGADORES",
        ["ui.market.action"] = "ARTÍCULO ELEGIDO",
        ["ui.market.buy"] = "Comprar ({0} de oro)",
        ["ui.market.take"] = "Fichar gratis",
        ["ui.market.hire"] = "Fichar (salario {0} por partido)",
        ["ui.market.sellButton"] = "Vender a {0} por {1} de oro",
        ["ui.market.badgeYouth"] = "CANT",
        ["ui.market.badgeMercenary"] = "MERC",
        ["ui.market.badgePlayer"] = "FICH",
        ["ui.market.badgePerk"] = "PERK",
        ["ui.market.badgeItem"] = "OBJ",
        ["ui.market.badgeConsumable"] = "CONS",
        ["ui.market.youthHint"] = "CANTERANO GRATIS: malo hoy y con un 33% más de experiencia; el crack del acto 3 sale de aquí (RF-114b, RF-114c)",
        ["ui.market.mercenaryHint"] = "MERCENARIO: sin coste de fichaje, {0} de salario por partido, y se marcha tras 3 partidos en el banquillo (RF-111)",
        ["ui.market.free"] = "gratis",
        ["ui.market.price"] = "{0} oro",
        ["ui.market.wage"] = "salario {0}",
        ["ui.market.cursedHint"] = "MALDITO: sube el doble y baja algo a cambio (ADR 0036)",
        ["ui.market.fragileHint"] = "FRÁGIL: {0}% de romperse al terminar cada partido (RF-077)",
        ["ui.market.restrictedHint"] = "EXCLUSIVO DE RAZA: no aporta nada a un portador que no sea {0}",
        ["ui.market.carrier"] = "QUIÉN LO LLEVA",
        ["ui.market.nothing"] = "elige un artículo de cualquiera de las cuatro columnas",
        ["ui.market.poor"] = "no te llega el oro: cuesta {0} y tienes {1}",
        ["ui.market.rosterFull"] = "plantilla llena ({0} de {1}): vende a alguien o compra un hueco en un nodo de inscripción (RF-020)",
        ["ui.market.noCarrier"] = "nadie de tu plantilla puede llevarlo",
        ["ui.market.leave"] = "Salir al mapa",
        ["ui.market.sellWarn"] = "quedan {0} disponibles: vender a uno más termina la run (RF-002b)",
        ["ui.market.sellRow"] = "{0} · nivel {1} · perks {2}",
        ["ui.market.empty"] = "sin artículos",
        ["ui.market.none"] = "no hay ningún mercado abierto",
        ["ui.market.error"] = "no se pudo: {0}",
        ["ui.input.mouseMatch"] = "RATÓN  clic en una ficha: seguirla · clic o arrastre en la barra: moverse por el partido · botones: pausa, velocidad y tick a tick",
        ["ui.input.padMatch"] = "MANDO  A: pausa y continuar · izquierda/derecha: un tick atrás o adelante · B: ir al informe",
        ["ui.input.mouseReport"] = "RATÓN  rueda: recorrer los perks activados · clic en Continuar para seguir",
        ["ui.input.mouseReward"] = "RATÓN  clic en una opción: elegirla · clic en un jugador: dársela",
        ["ui.input.mouseMarket"] = "RATÓN  clic en un artículo: verlo · clic en Comprar o en Vender para cerrar el trato",
        ["ui.market.sellNobody"] = "elige a quién vender en la lista",
    };

    /// <summary>Texto de la clave; si falta, la propia clave (un texto que falta debe verse, no ocultarse).</summary>
    public static string Get(string key) => Es.TryGetValue(key, out string? value) ? value : key;

    /// <summary>Texto de la clave con los argumentos sustituidos en <c>{0}</c>, <c>{1}</c>...</summary>
    public static string Get(string key, params object[] args) =>
        string.Format(System.Globalization.CultureInfo.InvariantCulture, Get(key), args);
}
